'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EarForgeLabs=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));
 function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
 function median(a){if(!a.length)return 0;const x=[...a].sort((a,b)=>a-b),m=x.length>>1;return x.length%2?x[m]:(x[m-1]+x[m])/2}
 function mad(a){if(!a.length)return 0;const m=median(a);return median(a.map(x=>Math.abs(x-m)))}
 function linearFit(y){const n=y.length;if(n<2)return{slope:0,intercept:y[0]||0};let sx=0,sy=0,sxx=0,sxy=0;for(let i=0;i<n;i++){sx+=i;sy+=y[i];sxx+=i*i;sxy+=i*y[i]}const d=n*sxx-sx*sx;if(!d)return{slope:0,intercept:sy/n};const slope=(n*sxy-sx*sy)/d;return{slope,intercept:(sy-slope*sx)/n}}
 function analyzeTaps(taps,{bpm=72,subdivision=1,startMs=null,phaseCalibrated=false}={}){
  const t=(taps||[]).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(t.length<4)return{valid:false,n:t.length,reason:'need_at_least_4_taps'};
  const target=60000/(clamp(bpm,20,300)*Math.max(1,subdivision)),ints=t.slice(1).map((x,i)=>x-t[i]),fit=linearFit(t),period=fit.slope,phaseReady=phaseCalibrated===true&&Number.isFinite(Number(startMs)),anchor=phaseReady?Number(startMs):fit.intercept,errors=t.map((x,i)=>x-(anchor+i*target)),residuals=t.map((x,i)=>x-(fit.intercept+i*period)),mae=mean(errors.map(Math.abs)),translationInvariantMae=mean(residuals.map(Math.abs)),jitter=mad(ints),driftPerBeat=period-target,stability=clamp(1-(mad(residuals)/(target*.18)+jitter/(target*.24))*.5,0,1),accuracyMae=phaseReady?mae:translationInvariantMae;
  const odd=ints.filter((_,i)=>i%2===0),even=ints.filter((_,i)=>i%2===1),swing=odd.length&&even.length?mean(odd)/Math.max(1,mean(even)):1;
  return{valid:true,n:t.length,targetIntervalMs:target,observedIntervalMs:period,meanAbsoluteDeviationMs:accuracyMae,translationInvariantMaeMs:translationInvariantMae,jitterMadMs:jitter,driftMsPerBeat:driftPerBeat,swingRatio:swing,pulseStability:stability,phaseCalibrated:phaseReady,phaseBiasMs:phaseReady?mean(errors):null,score:clamp(.60*stability+.25*(1-clamp(accuracyMae/(target*.25),0,1))+.15*(1-clamp(Math.abs(driftPerBeat)/(target*.06),0,1)),0,1)}
 }
 function analyzePolyrhythm(layerA,layerB,{bpm=72,ratioA=3,ratioB=2}={}){const a=analyzeTaps(layerA,{bpm,subdivision:ratioA}),b=analyzeTaps(layerB,{bpm,subdivision:ratioB});if(!a.valid||!b.valid)return{valid:false,a,b};const independence=clamp(1-Math.abs(a.driftMsPerBeat-b.driftMsPerBeat)/Math.max(a.targetIntervalMs,b.targetIntervalMs),0,1);return{valid:true,a,b,layerIndependence:independence,score:clamp(.42*a.score+.42*b.score+.16*independence,0,1)}}
 function contour(seq){const a=(seq||[]).map(Number);return a.slice(1).map((x,i)=>Math.sign(x-a[i]))}
 function levenshtein(a,b){const A=[...(a||[])],B=[...(b||[])],row=Array(B.length+1).fill(0).map((_,i)=>i);for(let i=1;i<=A.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=B.length;j++){const old=row[j],cost=A[i-1]===B[j-1]?0:1;row[j]=Math.min(row[j]+1,row[j-1]+1,prev+cost);prev=old}}return row[B.length]}
 function bestTransposition(reference,response){const A=(reference||[]).map(Number),B=(response||[]).map(Number);if(!A.length||!B.length)return 0;const n=Math.min(A.length,B.length),ds=[];for(let i=0;i<n;i++)ds.push(A[i]-B[i]);return Math.round(median(ds))}
 function analyzeMelodyRecall(reference,response,{allowTranspose=true}={}){const A=(reference||[]).map(Number),raw=(response||[]).map(Number);if(!A.length||!raw.length)return{valid:false,score:0};const shift=allowTranspose?bestTransposition(A,raw):0,B=raw.map(x=>x+shift),n=Math.max(A.length,B.length),edit=levenshtein(A.map(Math.round),B.map(Math.round)),pitchAccuracy=clamp(1-edit/Math.max(1,n),0,1),ca=contour(A),cb=contour(B),cn=Math.min(ca.length,cb.length),contourAccuracy=cn?ca.slice(0,cn).filter((x,i)=>x===cb[i]).length/Math.max(ca.length,cb.length):0;return{valid:true,transposition:shift,pitchAccuracy,contourAccuracy,lengthAccuracy:1-Math.abs(A.length-B.length)/Math.max(1,n),score:clamp(.58*pitchAccuracy+.30*contourAccuracy+.12*(1-Math.abs(A.length-B.length)/Math.max(1,n)),0,1)}}
 function continuationCandidates(sequence){const s=(sequence||[]).map(Number);if(s.length<2)return[];const last=s.at(-1),intervals=s.slice(1).map((x,i)=>x-s[i]),recent=intervals.slice(-3),trend=Math.sign(mean(recent)||0),repeat=recent.length>=2&&recent.at(-1)===recent.at(-2)?recent.at(-1):null,candidates=new Set();if(repeat!=null)candidates.add(last+repeat);candidates.add(last+(trend||1)*2);candidates.add(last+(trend||1));candidates.add(last-trend*2);return[...candidates].map(x=>({value:x,score:repeat!=null&&x===last+repeat?1:x===last+(trend||1)*2?.78:x===last+(trend||1)?.66:.42})).sort((a,b)=>b.score-a.score)}
 function alteredNote(reference,candidate){const A=reference||[],B=candidate||[],n=Math.min(A.length,B.length);const changes=[];for(let i=0;i<n;i++)if(Number(A[i])!==Number(B[i]))changes.push({index:i,delta:Number(B[i])-Number(A[i])});return{changes,count:changes.length,oneChanged:changes.length===1}}
 const FUNCTION={I:'T',i:'T',Imaj7:'T',Im7:'T',vi:'Tp',VI:'Tp',iii:'Tp',III:'Tp',IV:'S',iv:'S',ii:'Sp',ii7:'Sp','iiø7':'Sp',V:'D',V7:'D','V/ii':'D2','V/V':'D2',VII:'Dp',VII7:'Dp',subV7:'Dsub',bVII7:'S/D',ivm7:'Smin',ivm6:'Smin',bVImaj7:'Smin'};
 function harmonyAnalysis(roman){const r=(roman||[]).map(String),functions=r.map(x=>FUNCTION[x]||(/V\//.test(x)?'D2':'X'));let tension=0,resolutions=0,tonicizations=0;for(let i=0;i<functions.length-1;i++){const a=functions[i],b=functions[i+1];if(/^D/.test(a))tension++;if(/^D/.test(a)&&/^T/.test(b))resolutions++;if(a==='D2')tonicizations++}const tail=r.slice(-3).join('-'),last2=functions.slice(-2).join('>'),cadence=last2==='D>T'?'authentic':functions.slice(-3).join('>')==='S>D>T'||functions.slice(-3).join('>')==='Sp>D>T'?'cadential':'open';return{roman:r,functions,tensionEvents:tension,resolutions,tonicizations,cadence,functionalCoverage:functions.filter(x=>x!=='X').length/Math.max(1,functions.length)}}
 function voiceLeadingCost(chords){const C=(chords||[]).map(c=>(c||[]).map(Number).sort((a,b)=>a-b));let total=0,moves=0;for(let i=1;i<C.length;i++){const a=C[i-1],b=C[i],n=Math.min(a.length,b.length);for(let j=0;j<n;j++){let d=Math.abs(b[j]-a[j]);d=Math.min(d,Math.abs(d-12),Math.abs(d+12));total+=d;moves++}}return moves?total/moves:0}
 function normalizeMidiEvents(events){return(events||[]).map(e=>({time:Number(e.time??e.timestamp??0),type:e.type||((e.velocity??0)>0?'noteon':'noteoff'),note:Math.round(Number(e.note??e.data?.[1]??0)),velocity:clamp((e.velocity??e.data?.[2]??0)/((e.velocity??e.data?.[2]??0)>1?127:1),0,1),channel:Math.round(Number(e.channel??0))})).filter(e=>Number.isFinite(e.time)&&e.note>=0&&e.note<=127).sort((a,b)=>a.time-b.time)}
 function midiPerformance(events,{bpm=72}={}){const e=normalizeMidiEvents(events),on=e.filter(x=>x.type==='noteon'&&x.velocity>0);return{events:e,noteOns:on.length,timing:on.length>=4?analyzeTaps(on.map(x=>x.time),{bpm}):null,velocity:{mean:mean(on.map(x=>x.velocity)),spread:mad(on.map(x=>x.velocity))},notes:on.map(x=>x.note)}}
 function midiChordPerformance(events,{windowMs=70,bpm=72}={}){const e=normalizeMidiEvents(events),on=e.filter(x=>x.type==='noteon'&&x.velocity>0),groups=[];for(const n of on){let g=groups.at(-1);if(!g||n.time-g.start>windowMs){g={start:n.time,notes:[],velocities:[]};groups.push(g)}g.notes.push(n.note);g.velocities.push(n.velocity)}const chords=groups.filter(g=>g.notes.length>=2).map(g=>({time:g.start,notes:[...new Set(g.notes)].sort((a,b)=>a-b),size:new Set(g.notes).size,spread:Math.max(...g.notes)-Math.min(...g.notes),velocityMean:mean(g.velocities)}));return{...midiPerformance(events,{bpm}),chords,chordCount:chords.length,polyphony:chords.length?mean(chords.map(c=>c.size)):0}}
 function analyzeKeyAreas(areas){const a=(areas||[]).filter(x=>x&&typeof x==='object'&&x.key),changes=[];for(let i=1;i<a.length;i++)if(a[i].key!==a[i-1].key)changes.push({index:i,from:a[i-1].key,to:a[i].key,pivot:a[i].pivot||null});return{areas:a,modulations:changes.length,changes,stableTarget:Boolean(changes.length&&a.slice(changes.at(-1).index).filter(x=>x.key===changes.at(-1).to).length>=2)}}
 function harmonicTrial(seed='harmony'){const r=seeded(seed),trials=[{type:'resolution',label:'Tension puis résolution',roman:['ii7','V7','Imaj7'],chords:[[62,65,69,72],[55,59,62,65],[60,64,67,71]],areas:[{key:'C'},{key:'C'},{key:'C'}]},{type:'tonicization',label:'Tonicisation',roman:['I','V/ii','ii7','V7'],chords:[[60,64,67],[57,61,64,67],[62,65,69,72],[55,59,62,65]],areas:[{key:'C'},{key:'C'},{key:'C'},{key:'C'}]},{type:'substitution',label:'Substitution',roman:['ii7','subV7','Imaj7'],chords:[[62,65,69,72],[61,65,68,71],[60,64,67,71]],areas:[{key:'C'},{key:'C'},{key:'C'}]},{type:'modulation',label:'Modulation',roman:['I','vi','V/V','I@G','V7@G','I@G'],chords:[[60,64,67],[57,60,64],[62,66,69,72],[55,59,62],[62,66,69,72],[55,59,62,67]],areas:[{key:'C'},{key:'C',pivot:'vi'},{key:'C'},{key:'G',pivot:'V/V'},{key:'G'},{key:'G'}]}];return trials[Math.floor(r()*trials.length)]}
 function polyrhythmTrial({bpm=72,ratioA=3,ratioB=2,bars=4}={}){const beat=60000/bpm,total=bars*4*beat,a=[],b=[];for(let t=0;t<total-1;t+=beat/ratioA)a.push(t);for(let t=0;t<total-1;t+=beat/ratioB)b.push(t);return{bpm,ratioA,ratioB,bars,totalMs:total,layerA:a,layerB:b}}
 function seeded(seed){let a=2166136261>>>0;for(const c of String(seed)){a^=c.charCodeAt(0);a=Math.imul(a,16777619)}return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^a>>>15,1|a);t=(t+Math.imul(t^t>>>7,61|t))^t;return((t^t>>>14)>>>0)/4294967296}}
 function melodyTrial(seed='trial',difficulty=.5){const r=seeded(seed),len=5+Math.round(clamp(difficulty,0,1)*5),steps=[0];for(let i=1;i<len;i++){const jump=[-4,-2,-1,1,2,3,4][Math.floor(r()*7)];steps.push(clamp(steps.at(-1)+jump,-7,12))}const altered=[...steps],index=1+Math.floor(r()*Math.max(1,len-2)),delta=r()<.5?-1:1;altered[index]+=delta;return{reference:steps,altered,index,delta,delayMs:Math.round(600+clamp(difficulty,0,1)*5400),transpose:Math.floor(r()*7)-3}}
 function placementTargets(catalog,{limit=12}={}){const preferred=['interval:M3:asc','interval:m3:asc','rhythm:pulse4','rhythm:eighths','chord:maj:root','chord:min:root','scale:major','scale:natmin','degree:maj:5','progression:I-V-I','melody:rise','tuning:35:0'];return preferred.map(id=>catalog?.byId?.[id]).filter(Boolean).slice(0,limit)}
 return{analyzeTaps,analyzePolyrhythm,analyzeMelodyRecall,continuationCandidates,alteredNote,harmonyAnalysis,voiceLeadingCost,normalizeMidiEvents,midiPerformance,midiChordPerformance,analyzeKeyAreas,harmonicTrial,polyrhythmTrial,melodyTrial,placementTargets};
});
