'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EarForgeLabs=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));
 function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
 function median(a){if(!a.length)return 0;const x=[...a].sort((a,b)=>a-b),m=x.length>>1;return x.length%2?x[m]:(x[m-1]+x[m])/2}
 function mad(a){if(!a.length)return 0;const m=median(a);return median(a.map(x=>Math.abs(x-m)))}
 function linearFit(y){const n=y.length;if(n<2)return{slope:0,intercept:y[0]||0};let sx=0,sy=0,sxx=0,sxy=0;for(let i=0;i<n;i++){sx+=i;sy+=y[i];sxx+=i*i;sxy+=i*y[i]}const d=n*sxx-sx*sx;if(!d)return{slope:0,intercept:sy/n};const slope=(n*sxy-sx*sy)/d;return{slope,intercept:(sy-slope*sx)/n}}
 function analyzeTaps(taps,{bpm=72,subdivision=1,startMs=null,phaseCalibrated=false}={}){
  const t=(taps||[]).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(t.length<4)return{valid:false,n:t.length,reason:'need_at_least_4_taps'};
  const target=60000/(clamp(bpm,20,300)*Math.max(1,subdivision)),ints=t.slice(1).map((x,i)=>x-t[i]),fit=linearFit(t),period=fit.slope,phaseReady=phaseCalibrated===true&&Number.isFinite(Number(startMs)),anchor=phaseReady?Number(startMs):fit.intercept,errors=t.map((x,i)=>x-(anchor+i*target)),residuals=t.map((x,i)=>x-(fit.intercept+i*period)),mae=mean(errors.map(Math.abs)),translationInvariantMae=mean(residuals.map(Math.abs)),jitter=mad(ints),driftPerBeat=period-target,stability=clamp(1-(mad(residuals)/(target*.18)+jitter/(target*.24))*.5,0,1),accuracyMae=phaseReady?mae:translationInvariantMae;
  const odd=ints.filter((_,i)=>i%2===0),even=ints.filter((_,i)=>i%2===1),swing=odd.length&&even.length?mean(odd)/Math.max(1,mean(even)):1;
  return{valid:true,n:t.length,targetIntervalMs:target,observedIntervalMs:period,meanAbsoluteDeviationMs:accuracyMae,translationInvariantMaeMs:translationInvariantMae,jitterMadMs:jitter,driftMsPerBeat:driftPerBeat,swingRatio:swing,pulseStability:stability,phaseCalibrated:phaseReady,phaseBiasMs:phaseReady?mean(errors):null,score:clamp(.60*stability+.25*(1-clamp(accuracyMae/(target*.25),0,1))+.15*(1-clamp(Math.abs(driftPerBeat)/(target*.06),0,1)),0,1)}
 }
 function analyzePolyrhythm(layerA,layerB,{bpm=72,ratioA=3,ratioB=2}={}){const a=analyzeTaps(layerA,{bpm,subdivision:ratioA}),b=analyzeTaps(layerB,{bpm,subdivision:ratioB});if(!a.valid||!b.valid)return{valid:false,a,b};const independence=clamp(1-Math.abs(a.driftMsPerBeat-b.driftMsPerBeat)/Math.max(a.targetIntervalMs,b.targetIntervalMs),0,1);return{valid:true,a,b,layerIndependence:independence,score:clamp(.42*a.score+.42*b.score+.16*independence,0,1)}}
 function analyzeConcurrentPolyrhythm(layerA,layerB,{bpm=72,ratioA=3,ratioB=2,startMs=null,phaseCalibrated=false}={}){const a=analyzeTaps(layerA,{bpm,subdivision:ratioA,startMs,phaseCalibrated}),b=analyzeTaps(layerB,{bpm,subdivision:ratioB,startMs,phaseCalibrated});if(!a.valid||!b.valid)return{valid:false,mode:'simultaneous',a,b,layerIndependence:0,score:0};const driftAgreement=clamp(1-Math.abs(a.driftMsPerBeat-b.driftMsPerBeat)/Math.max(a.targetIntervalMs,b.targetIntervalMs),0,1),phaseAgreement=phaseCalibrated&&Number.isFinite(a.phaseBiasMs)&&Number.isFinite(b.phaseBiasMs)?clamp(1-Math.abs(a.phaseBiasMs-b.phaseBiasMs)/Math.max(a.targetIntervalMs,b.targetIntervalMs),0,1):null,independence=phaseAgreement==null?driftAgreement:clamp(.58*driftAgreement+.42*phaseAgreement,0,1),score=clamp(.40*a.score+.40*b.score+.20*independence,0,1);return{valid:true,mode:'simultaneous',a,b,driftAgreement,phaseAgreement,layerIndependence:independence,score}}
 function midiProductionReliability(events,{inputs=1}={}){const e=normalizeMidiEvents(events),on=e.filter(x=>x.type==='noteon'&&x.velocity>0),times=e.map(x=>x.time),monotonic=times.every((x,i)=>i===0||x>=times[i-1]),timestamps=times.filter(Number.isFinite).length===times.length,density=clamp(on.length/8,0,1),inputEvidence=clamp(Number(inputs)||0,0,4)/4,reliability=clamp(.45*(monotonic&&timestamps?1:0)+.40*density+.15*inputEvidence,0,1);return{valid:on.length>0,events:e.length,noteOns:on.length,monotonic,timestamps,inputs:Math.max(0,Math.round(Number(inputs)||0)),reliability,plannerEligible:false,microphoneRequired:false}}
 function contour(seq){const a=(seq||[]).map(Number);return a.slice(1).map((x,i)=>Math.sign(x-a[i]))}
 function levenshtein(a,b){const A=[...(a||[])],B=[...(b||[])],row=Array(B.length+1).fill(0).map((_,i)=>i);for(let i=1;i<=A.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=B.length;j++){const old=row[j],cost=A[i-1]===B[j-1]?0:1;row[j]=Math.min(row[j]+1,row[j-1]+1,prev+cost);prev=old}}return row[B.length]}
 function bestTransposition(reference,response){const A=(reference||[]).map(Number),B=(response||[]).map(Number);if(!A.length||!B.length)return 0;const n=Math.min(A.length,B.length),ds=[];for(let i=0;i<n;i++)ds.push(A[i]-B[i]);return Math.round(median(ds))}
 function analyzeMelodyRecall(reference,response,{allowTranspose=true}={}){const A=(reference||[]).map(Number),raw=(response||[]).map(Number);if(!A.length||!raw.length)return{valid:false,score:0};const shift=allowTranspose?bestTransposition(A,raw):0,B=raw.map(x=>x+shift),n=Math.max(A.length,B.length),edit=levenshtein(A.map(Math.round),B.map(Math.round)),pitchAccuracy=clamp(1-edit/Math.max(1,n),0,1),ca=contour(A),cb=contour(B),cn=Math.min(ca.length,cb.length),contourAccuracy=cn?ca.slice(0,cn).filter((x,i)=>x===cb[i]).length/Math.max(ca.length,cb.length):0;return{valid:true,transposition:shift,pitchAccuracy,contourAccuracy,lengthAccuracy:1-Math.abs(A.length-B.length)/Math.max(1,n),score:clamp(.58*pitchAccuracy+.30*contourAccuracy+.12*(1-Math.abs(A.length-B.length)/Math.max(1,n)),0,1)}}
 function semanticSequence(input){if(Array.isArray(input))return input.map(Number).filter(Number.isFinite);const e=input?.events;if(!Array.isArray(e))return[];const out=[];for(const x of e)if(x?.type==='pitched')for(const n of x.notes||[])if(Number.isFinite(Number(n)))out.push(Number(n));return out}
 function semanticOnsets(input){const ppq=Number(input?.ppq)||960,e=input?.events;if(!Array.isArray(e))return[];return e.filter(x=>x?.role!=='context').map(x=>Number(x.onsetTicks)/ppq).filter(Number.isFinite)}
 function analyzeSemanticDictation(reference,response,{allowTranspose=true}={}){const A=semanticSequence(reference),B=semanticSequence(response),pitch=A.length&&B.length?analyzeMelodyRecall(A,B,{allowTranspose}):null,oa=semanticOnsets(reference),ob=semanticOnsets(response);let timing=null;if(oa.length&&ob.length){const n=Math.min(oa.length,ob.length),a=oa.slice(0,n),b=ob.slice(0,n),shift=b[0]-a[0],errors=b.map((x,i)=>x-shift-a[i]),mae=mean(errors.map(Math.abs)),lengthAccuracy=1-Math.abs(oa.length-ob.length)/Math.max(oa.length,ob.length);timing={matched:n,meanAbsoluteBeatError:mae,lengthAccuracy:clamp(lengthAccuracy,0,1),score:clamp(.72*(1-clamp(mae/.5,0,1))+.28*clamp(lengthAccuracy,0,1),0,1)}}const score=(pitch&&timing&&timing.score!=null)?.65*pitch.score+.35*timing.score:pitch?pitch.score:(timing?.score??0);return{valid:Boolean(pitch||timing),pitch,timing,score:clamp(score,0,1),visualRequired:false}}
 function responseChannels(capabilities={}){const c=capabilities||{};const core=['choice','semantic_sequence'],optional=[];if(c.tap)optional.push('tap');if(c.midi)optional.push('midi');if(c.braille)optional.push('braille');if(c.visual)optional.push('visual_notation');return{core,optional,masteryBlocked:false,visualRequired:false}}
 function continuationCandidates(sequence){const s=(sequence||[]).map(Number);if(s.length<2)return[];const last=s.at(-1),intervals=s.slice(1).map((x,i)=>x-s[i]),recent=intervals.slice(-3),trend=Math.sign(mean(recent)||0),repeat=recent.length>=2&&recent.at(-1)===recent.at(-2)?recent.at(-1):null,candidates=new Set();if(repeat!=null)candidates.add(last+repeat);candidates.add(last+(trend||1)*2);candidates.add(last+(trend||1));candidates.add(last-trend*2);return[...candidates].map(x=>({value:x,score:repeat!=null&&x===last+repeat?1:x===last+(trend||1)*2?.78:x===last+(trend||1)?.66:.42})).sort((a,b)=>b.score-a.score)}
 function alteredNote(reference,candidate){const A=reference||[],B=candidate||[],n=Math.min(A.length,B.length);const changes=[];for(let i=0;i<n;i++)if(Number(A[i])!==Number(B[i]))changes.push({index:i,delta:Number(B[i])-Number(A[i])});return{changes,count:changes.length,oneChanged:changes.length===1}}
 const FUNCTION={I:'T',i:'T',Imaj7:'T',Im7:'T',vi:'Tp',VI:'Tp',iii:'Tp',III:'Tp',IV:'S',iv:'S',ii:'Sp',ii7:'Sp','iiø7':'Sp',V:'D',V7:'D','V/ii':'D2','V/V':'D2',VII:'Dp',VII7:'Dp',subV7:'Dsub',bVII7:'S/D',ivm7:'Smin',ivm6:'Smin',bVImaj7:'Smin'};
 function harmonyAnalysis(roman){const r=(roman||[]).map(String),functions=r.map(x=>FUNCTION[x]||(/V\//.test(x)?'D2':'X'));let tension=0,resolutions=0,tonicizations=0;for(let i=0;i<functions.length-1;i++){const a=functions[i],b=functions[i+1];if(/^D/.test(a))tension++;if(/^D/.test(a)&&/^T/.test(b))resolutions++;if(a==='D2')tonicizations++}const tail=r.slice(-3).join('-'),last2=functions.slice(-2).join('>'),cadence=last2==='D>T'?'authentic':functions.slice(-3).join('>')==='S>D>T'||functions.slice(-3).join('>')==='Sp>D>T'?'cadential':'open';return{roman:r,functions,tensionEvents:tension,resolutions,tonicizations,cadence,functionalCoverage:functions.filter(x=>x!=='X').length/Math.max(1,functions.length)}}
 function voiceLeadingCost(chords){const C=(chords||[]).map(c=>(c||[]).map(Number).sort((a,b)=>a-b));let total=0,moves=0;for(let i=1;i<C.length;i++){const a=C[i-1],b=C[i],n=Math.min(a.length,b.length);for(let j=0;j<n;j++){let d=Math.abs(b[j]-a[j]);d=Math.min(d,Math.abs(d-12),Math.abs(d+12));total+=d;moves++}}return moves?total/moves:0}
 function normalizeMidiEvents(events){return(events||[]).map(e=>({time:Number(e.time??e.timestamp??0),type:e.type||((e.velocity??0)>0?'noteon':'noteoff'),note:Math.round(Number(e.note??e.data?.[1]??0)),velocity:clamp((e.velocity??e.data?.[2]??0)/((e.velocity??e.data?.[2]??0)>1?127:1),0,1),channel:Math.round(Number(e.channel??0))})).filter(e=>Number.isFinite(e.time)&&e.note>=0&&e.note<=127).sort((a,b)=>a.time-b.time)}
 function midiPerformance(events,{bpm=72}={}){const e=normalizeMidiEvents(events),on=e.filter(x=>x.type==='noteon'&&x.velocity>0);return{events:e,noteOns:on.length,timing:on.length>=4?analyzeTaps(on.map(x=>x.time),{bpm}):null,velocity:{mean:mean(on.map(x=>x.velocity)),spread:mad(on.map(x=>x.velocity))},notes:on.map(x=>x.note)}}
 function midiChordPerformance(events,{windowMs=70,bpm=72}={}){const e=normalizeMidiEvents(events),on=e.filter(x=>x.type==='noteon'&&x.velocity>0),groups=[];for(const n of on){let g=groups.at(-1);if(!g||n.time-g.start>windowMs){g={start:n.time,notes:[],velocities:[]};groups.push(g)}g.notes.push(n.note);g.velocities.push(n.velocity)}const base=midiPerformance(events,{bpm}),onsetTimes=groups.map(g=>g.start),chords=groups.filter(g=>g.notes.length>=2).map(g=>({time:g.start,notes:[...new Set(g.notes)].sort((a,b)=>a-b),size:new Set(g.notes).size,spread:Math.max(...g.notes)-Math.min(...g.notes),velocityMean:mean(g.velocities)}));return{...base,timing:onsetTimes.length>=4?analyzeTaps(onsetTimes,{bpm}):null,onsetGroups:groups.length,noteGroups:groups.map(g=>({time:g.start,notes:[...new Set(g.notes)].sort((a,b)=>a-b),velocityMean:mean(g.velocities)})),chords,chordCount:chords.length,polyphony:chords.length?mean(chords.map(c=>c.size)):0}}
 function analyzeKeyAreas(areas){const a=(areas||[]).filter(x=>x&&typeof x==='object'&&x.key),changes=[];for(let i=1;i<a.length;i++)if(a[i].key!==a[i-1].key)changes.push({index:i,from:a[i-1].key,to:a[i].key,pivot:a[i].pivot||null});return{areas:a,modulations:changes.length,changes,stableTarget:Boolean(changes.length&&a.slice(changes.at(-1).index).filter(x=>x.key===changes.at(-1).to).length>=2)}}
 function harmonicTrial(seed='harmony'){const r=seeded(seed),trials=[
  {type:'resolution',label:'Tension puis résolution',question:'La tension se résout-elle vers un point de repos ?',choices:['Tension puis résolution','Tonicisation'],roman:['ii7','V7','Imaj7'],chords:[[62,65,69,72],[55,59,62,65],[60,64,67,71]],areas:[{key:'C'},{key:'C'},{key:'C'}]},
  {type:'tonicization',label:'Tonicisation',question:'Entendez-vous un bref accord dominant dirigé vers un accord local, sans nouveau centre durable ?',choices:['Tonicisation','Modulation'],roman:['I','V/ii','ii7','V7'],chords:[[60,64,67],[57,61,64,67],[62,65,69,72],[55,59,62,65]],areas:[{key:'C'},{key:'C'},{key:'C'},{key:'C'}]},
  {type:'substitution',label:'Substitution',question:'Le chemin vers l’accord final utilise-t-il une substitution chromatique ?',choices:['Substitution','Tension puis résolution'],roman:['ii7','subV7','Imaj7'],chords:[[62,65,69,72],[61,65,68,71],[60,64,67,71]],areas:[{key:'C'},{key:'C'},{key:'C'}]},
  {type:'modulation',label:'Modulation',question:'Le point de repos change-t-il durablement ?',choices:['Modulation','Tonicisation'],roman:['I','vi','V/V','I@G','V7@G','I@G'],chords:[[60,64,67],[57,60,64],[62,66,69,72],[55,59,62],[62,66,69,72],[55,59,62,67]],areas:[{key:'C'},{key:'C',pivot:'vi'},{key:'C'},{key:'G',pivot:'V/V'},{key:'G'},{key:'G'}]}
 ];const trial=trials[Math.floor(r()*trials.length)];return{...trial,minimalDiscriminator:true,chance:1/trial.choices.length}}
 function polyrhythmTrial({bpm=72,ratioA=3,ratioB=2,bars=4}={}){const beat=60000/bpm,total=bars*4*beat,a=[],b=[];for(let t=0;t<total-1;t+=beat/ratioA)a.push(t);for(let t=0;t<total-1;t+=beat/ratioB)b.push(t);return{bpm,ratioA,ratioB,bars,totalMs:total,layerA:a,layerB:b}}
 function seeded(seed){let a=2166136261>>>0;for(const c of String(seed)){a^=c.charCodeAt(0);a=Math.imul(a,16777619)}return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^a>>>15,1|a);t=(t+Math.imul(t^t>>>7,61|t))^t;return((t^t>>>14)>>>0)/4294967296}}
 function melodyTrial(seed='trial',difficulty=.5){const r=seeded(seed),len=5+Math.round(clamp(difficulty,0,1)*5),steps=[0];for(let i=1;i<len;i++){const jump=[-4,-2,-1,1,2,3,4][Math.floor(r()*7)];steps.push(clamp(steps.at(-1)+jump,-7,12))}const altered=[...steps],index=1+Math.floor(r()*Math.max(1,len-2)),delta=r()<.5?-1:1;altered[index]+=delta;return{reference:steps,altered,index,delta,delayMs:Math.round(600+clamp(difficulty,0,1)*5400),transpose:Math.floor(r()*7)-3}}
 const DEFAULT_INTONATION_MIN=3,DEFAULT_INTONATION_MAX=60,INTONATION_POINTS=41;
 function logGrid(min,max,n=INTONATION_POINTS){const lo=Math.max(.25,Number(min)||DEFAULT_INTONATION_MIN),hi=Math.max(lo*1.1,Number(max)||DEFAULT_INTONATION_MAX),steps=Math.max(9,Math.round(n)||INTONATION_POINTS);return Array.from({length:steps},(_,i)=>lo*Math.exp(Math.log(hi/lo)*i/(steps-1)))}
 function intonationPsychometric(level,threshold,{slope=2,lapse=.02}={}){const d=Math.max(.1,Number(level)||0),t=Math.max(.1,Number(threshold)||1),core=.5+.5*(1-Math.exp(-Math.log(2)*Math.pow(d/t,slope)));return clamp(.5+(core-.5)*(1-2*clamp(lapse,0,.2)),.500001,.999999)}
 function normalizePosterior(weights){const a=(weights||[]).map(x=>Math.max(0,Number(x)||0)),sum=a.reduce((x,y)=>x+y,0)||1;return a.map(x=>x/sum)}
 function posteriorEntropy(weights){let h=0;for(const x of weights||[])if(x>0)h-=x*Math.log(x);return h}
 function intonationGrid(state){return logGrid(state?.domainMin??DEFAULT_INTONATION_MIN,state?.domainMax??DEFAULT_INTONATION_MAX,INTONATION_POINTS)}
 function posteriorFromHistory(history,grid,prior=null){let w=normalizePosterior(prior&&prior.length===grid.length?prior:Array(grid.length).fill(1/grid.length));for(const row of history||[]){const level=Math.max(.1,Number(row?.cents)||0),ps=grid.map(t=>intonationPsychometric(level,t)),correct=Boolean(row?.correct);w=normalizePosterior(w.map((x,i)=>x*(correct?ps[i]:1-ps[i])))}return w}
 function adaptiveIntonationStart({maxTrials=12,domainMin=DEFAULT_INTONATION_MIN,domainMax=DEFAULT_INTONATION_MAX}={}){const n=Math.max(8,Math.min(28,Math.round(maxTrials)||12)),min=Math.max(.25,Number(domainMin)||DEFAULT_INTONATION_MIN),max=Math.max(min*4,Number(domainMax)||DEFAULT_INTONATION_MAX),grid=logGrid(min,max);return{schema:'earforge.intonation_bayes.v2',trial:0,maxTrials:n,domainMin:min,domainMax:max,weights:Array(grid.length).fill(1/grid.length),history:[],domainExpansions:0,boundaryStable:true}}
 function boundaryMass(weights){const w=normalizePosterior(weights),k=Math.max(2,Math.round(w.length*.08));return{low:w.slice(0,k).reduce((a,b)=>a+b,0),high:w.slice(-k).reduce((a,b)=>a+b,0)}}
 function intonationPredictiveLogScore(history,grid){const rows=[...(history||[])],split=Math.max(4,rows.length-4);if(rows.length<8)return 0;let w=Array(grid.length).fill(1/grid.length),score=0;for(let j=0;j<rows.length;j++){const row=rows[j],ps=grid.map(t=>intonationPsychometric(row.cents,t)),pred=clamp(w.reduce((a,x,i)=>a+x*ps[i],0),1e-6,1-1e-6);if(j>=split)score+=Math.log(row.correct?pred:1-pred);w=normalizePosterior(w.map((x,i)=>x*(row.correct?ps[i]:1-ps[i])))}return score}
 function adaptiveIntonationEstimate(state){const grid=intonationGrid(state),w=normalizePosterior(state?.weights?.length===grid.length?state.weights:posteriorFromHistory(state?.history,grid)),outsideProbability=w.reduce((a,x,i)=>a+(grid[i]<DEFAULT_INTONATION_MIN*.999||grid[i]>DEFAULT_INTONATION_MAX*1.001?x:0),0),originalGrid=logGrid(DEFAULT_INTONATION_MIN,DEFAULT_INTONATION_MAX,INTONATION_POINTS),domainEvidenceGain=(Number(state?.domainExpansions)||0)>0?intonationPredictiveLogScore(state?.history,grid)-intonationPredictiveLogScore(state?.history,originalGrid):0,useExpanded=(Number(state?.domainExpansions)||0)>0&&outsideProbability>=.25&&domainEvidenceGain>.80,reportGrid=useExpanded?grid:originalGrid,reportW=useExpanded?w:posteriorFromHistory(state?.history,reportGrid),q0=p=>{let c=0;for(let i=0;i<reportW.length;i++){c+=reportW[i];if(c>=p)return reportGrid[i]}return reportGrid.at(-1)},fallback=!useExpanded&&state?.fallbackEstimate?state.fallbackEstimate:null,estimate=fallback?.estimateCents??Math.exp(reportW.reduce((a,x,i)=>a+x*Math.log(reportGrid[i]),0)),q=p=>p===.10&&fallback?.lowerCents!=null?fallback.lowerCents:p===.90&&fallback?.upperCents!=null?fallback.upperCents:q0(p),edge=boundaryMass(w),trial=Math.max(0,Number(state?.trial)||0),maxTrials=Math.max(8,Number(state?.maxTrials)||12),boundaryStable=edge.low<.55&&edge.high<.55,boundaryCapped=(grid[0]<=.251&&edge.low>=.55)||(grid.at(-1)>=319.5&&edge.high>=.55);return{estimateCents:estimate,lowerCents:q(.10),upperCents:q(.90),trials:trial,maxTrials,complete:trial>=maxTrials&&(boundaryStable||boundaryCapped),domainMin:grid[0],domainMax:grid.at(-1),boundaryMass:edge,boundaryStable,boundaryCapped,outsideProbability,domainEvidenceGain,expandedEstimateUsed:useExpanded,domainExpansions:Number(state?.domainExpansions)||0}}
 function maybeExpandIntonation(state){if((state?.trial||0)<Math.max(8,Number(state?.maxTrials)||12))return state;const grid=intonationGrid(state),w=normalizePosterior(state?.weights?.length===grid.length?state.weights:posteriorFromHistory(state?.history,grid)),edge=boundaryMass(w);let min=grid[0],max=grid.at(-1),expanded=false;if(edge.low>=.35&&min>.251){const next=Math.max(.25,min/2.5);if(next<min*.99){min=next;expanded=true}}if(edge.high>=.35&&max<319.5){const next=Math.min(320,max*2.5);if(next>max*1.01){max=next;expanded=true}}if(!expanded)return{...state,boundaryStable:true};const oldQ=p=>{let c=0;for(let i=0;i<w.length;i++){c+=w[i];if(c>=p)return grid[i]}return grid.at(-1)},fallbackEstimate=state.fallbackEstimate||{estimateCents:Math.exp(w.reduce((a,x,i)=>a+x*Math.log(grid[i]),0)),lowerCents:oldQ(.10),upperCents:oldQ(.90)},nextGrid=logGrid(min,max),history=[...(state.history||[])],oldMin=grid[0],oldMax=grid.at(-1),inside=nextGrid.map(x=>x>=oldMin*.999&&x<=oldMax*1.001),insideN=inside.filter(Boolean).length,outsideN=inside.length-insideN,reserve=outsideN?0.15:0,prior=inside.map(ok=>ok?(1-reserve)/Math.max(1,insideN):reserve/Math.max(1,outsideN));return{...state,fallbackEstimate,domainMin:min,domainMax:max,weights:posteriorFromHistory(history,nextGrid,prior),maxTrials:Math.min(28,Math.max(Number(state.maxTrials)||12,(Number(state.trial)||0)+8)),domainExpansions:(Number(state.domainExpansions)||0)+1,boundaryStable:false}}
 function adaptiveIntonationNext(state){const grid=intonationGrid(state),w=normalizePosterior(state?.weights?.length===grid.length?state.weights:posteriorFromHistory(state?.history,grid)),levels=logGrid(grid[0],grid.at(-1),15);let best=levels[0],bestEntropy=Infinity;for(const level of levels){const ps=grid.map(t=>intonationPsychometric(level,t)),pc=w.reduce((a,x,i)=>a+x*ps[i],0),wc=normalizePosterior(w.map((x,i)=>x*ps[i])),ww=normalizePosterior(w.map((x,i)=>x*(1-ps[i]))),expected=pc*posteriorEntropy(wc)+(1-pc)*posteriorEntropy(ww);if(expected<bestEntropy){bestEntropy=expected;best=level}}return{cents:Math.round(best*10)/10,expectedEntropy:bestEntropy,...adaptiveIntonationEstimate(state)}}
 function adaptiveIntonationUpdate(state,{cents,correct}={}){const grid=intonationGrid(state),level=Math.max(.2,Math.min(400,Number(cents)||0)),w=normalizePosterior(state?.weights?.length===grid.length?state.weights:posteriorFromHistory(state?.history,grid)),ps=grid.map(t=>intonationPsychometric(level,t)),weights=normalizePosterior(w.map((x,i)=>x*(correct?ps[i]:1-ps[i]))),history=[...(state?.history||[]),{cents:level,correct:Boolean(correct)}].slice(-40),raw={...state,trial:Math.max(0,Number(state?.trial)||0)+1,weights,history},next=maybeExpandIntonation(raw);return{state:next,...adaptiveIntonationEstimate(next)}}
 function adaptiveIntonationTrial(state,seed='intonation'){const next=adaptiveIntonationNext(state),r=seeded(`${seed}:${state?.trial||0}`),sign=r()<.5?-1:1;return{...next,sign,offsetCents:sign*next.cents,answer:sign<0?'low':'high'}}
 function timingCapabilitySnapshot({audioTiming=null,midiAvailable=false,touchAvailable=true}={}){return{terminal:{clock:'performance.now',physicalLatencyMeasured:false,compensationMs:0},touch:{clock:'PointerEvent.timeStamp',available:Boolean(touchAvailable),physicalLatencyMeasured:false,compensationMs:0},midi:{clock:'MIDIMessageEvent.timeStamp',available:Boolean(midiAvailable),physicalLatencyMeasured:false,compensationMs:0},audio:{clock:audioTiming?.method||'unknown',calibrated:Boolean(audioTiming?.calibrated),baseLatencyMs:Number.isFinite(Number(audioTiming?.baseLatencyMs))?Number(audioTiming.baseLatencyMs):null,outputLatencyMs:Number.isFinite(Number(audioTiming?.outputLatencyMs))?Number(audioTiming.outputLatencyMs):null,physicalOutputTimestamp:Boolean(audioTiming?.calibrated),compensationMs:0},bluetooth:{universalCompensationApplied:false,compensationMs:0}}}
 function routeTimingSample(route,eventTime,receivedTime){const event=Number(eventTime),received=Number(receivedTime);return{route:String(route||'terminal'),eventTime:Number.isFinite(event)?event:null,receivedTime:Number.isFinite(received)?received:null,deliveryLagMs:Number.isFinite(event)&&Number.isFinite(received)?Math.max(0,received-event):null,compensationMs:0}}
 function summarizeRouteTiming(samples,audioTiming=null){const groups={};for(const row of samples||[]){if(!row||!row.route)continue;(groups[row.route]??=[]).push(row)}const routes={};for(const [route,rows] of Object.entries(groups)){const lags=rows.map(x=>Number(x.deliveryLagMs)).filter(Number.isFinite);routes[route]={n:rows.length,deliveryLagMedianMs:lags.length?median(lags):null,deliveryLagMadMs:lags.length?mad(lags):null,physicalLatencyMeasured:false,compensationMs:0}}return{capabilities:timingCapabilitySnapshot({audioTiming,midiAvailable:Boolean(groups.midi?.length),touchAvailable:true}),routes,unmeasuredBluetoothCompensation:false}}
 function placementTargets(catalog,{limit=12}={}){const preferred=['interval:M3:asc','interval:m3:asc','rhythm:pulse4','rhythm:eighths','chord:maj:root','chord:min:root','scale:major','scale:natmin','degree:maj:5','progression:I-V-I','melody:rise','tuning:35:0'];return preferred.map(id=>catalog?.byId?.[id]).filter(Boolean).slice(0,limit)}
 return{analyzeTaps,analyzePolyrhythm,analyzeConcurrentPolyrhythm,analyzeMelodyRecall,analyzeSemanticDictation,semanticSequence,semanticOnsets,responseChannels,continuationCandidates,alteredNote,harmonyAnalysis,voiceLeadingCost,normalizeMidiEvents,midiPerformance,midiChordPerformance,midiProductionReliability,analyzeKeyAreas,harmonicTrial,polyrhythmTrial,melodyTrial,adaptiveIntonationStart,adaptiveIntonationNext,adaptiveIntonationUpdate,adaptiveIntonationEstimate,adaptiveIntonationTrial,intonationPsychometric,timingCapabilitySnapshot,routeTimingSample,summarizeRouteTiming,placementTargets};
});
