'use strict';
(function(root,factory){
  const release=typeof module==='object'&&module.exports?require('./release.json'):(root.EarForgeRelease||{});
  const api=factory(release);
  if(typeof module==='object'&&module.exports)module.exports=api;
  else root.EarForgeFrontiers=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(release){
  const VERSION=String(release.version||'unknown');
  const SCHEMA='earforge.frontiers.v2';
  const PPQ=960;
  const SESSION_SCOPE='session_local_not_tradition_model';
  const clamp=(value,min,max)=>Math.min(max,Math.max(min,Number(value)||0));
  const finite=value=>Number.isFinite(Number(value));
  const mean=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0;
  function median(values){if(!values.length)return 0;const rows=[...values].map(Number).filter(Number.isFinite).sort((a,b)=>a-b),m=rows.length>>1;return rows.length%2?rows[m]:(rows[m-1]+rows[m])/2}
  function unique(values){return[...new Set(values)]}
  function choose(random,values){return values[Math.min(values.length-1,Math.floor(random()*values.length))]}
  function shuffle(random,values){const out=[...values];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  function canonical(value){if(value===null||typeof value!=='object')return value;if(Array.isArray(value))return value.map(canonical);const out={};for(const key of Object.keys(value).sort())out[key]=canonical(value[key]);return out}
  function stableStringify(value){return JSON.stringify(canonical(value))}
  function hash32(value){const text=typeof value==='string'?value:stableStringify(value);let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
  function deepFreeze(value){if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child)}return value}
  function event(notes,onsetBeats,durationBeats,velocity=.72,{role='target',timbre='piano',articulation='normal',cents=0,type='pitched',instrument='',spectralProfile=''}={}){return{type,notes:Array.isArray(notes)?notes:[notes],onsetTicks:Math.round(onsetBeats*PPQ),durationTicks:Math.max(30,Math.round(durationBeats*PPQ)),velocity:clamp(velocity,.08,1),articulation,gate:{staccato:.38,detache:.62,tenuto:.92,legato:1.02,accent:.72,normal:.84}[articulation]||.84,cents,role,timbre,instrument,spectralProfile}}
  function score(events,tempo=72){const normalized=events.map(row=>({...row,notes:[...(row.notes||[])]})),endTicks=normalized.reduce((m,row)=>Math.max(m,(Number(row.onsetTicks)||0)+(Number(row.durationTicks)||1)*Math.max(.35,Number(row.gate)||1)),0);return{ppq:PPQ,tempo:clamp(tempo,36,180),events:normalized,endTicks:Math.ceil(endTicks)}}
  function unit(def){return{module:'core',difficulty:.82,stage:50,variationAxes:['tonic','register','tempo','timbre','dynamic'],renderContexts:['controlled'],identityContracts:{answerInvariant:true,visualRequired:false},responseModes:['choice','semantic_sequence'],questionOperations:['IDENTIFY','DISCRIMINATE','COMPARE_VARIANTS'],...def,frontierContract:{version:1,visualRequired:false,scope:'controlled_auditory_measurement',...(def.frontierContract||{})}}}

  const UNITS=deepFreeze([
    unit({id:'scene:upper-change',family:'scene',kind:'scene',group:'scene.tracking',label:'Voix supérieure modifiée',stage:41,difficulty:.82,prereq:['voice:outer-motion','texture:polyphonic-independence'],generatorContract:'scene.stream',judgeContract:'scene.role-change',audibleInvariant:'identité de la source supérieure à travers deux scènes',params:{code:'upper-change',targetRole:'upper'},frontierContract:{capability:'scene_hearing',oracle:'changed_role=upper'}}),
    unit({id:'scene:lower-change',family:'scene',kind:'scene',group:'scene.tracking',label:'Voix inférieure modifiée',stage:42,difficulty:.83,prereq:['scene:upper-change','bass:inversion-function'],generatorContract:'scene.stream',judgeContract:'scene.role-change',audibleInvariant:'identité de la source inférieure à travers deux scènes',params:{code:'lower-change',targetRole:'lower'},frontierContract:{capability:'scene_hearing',oracle:'changed_role=lower'}}),
    unit({id:'scene:inner-change',family:'scene',kind:'scene',group:'scene.tracking',label:'Voix intérieure modifiée',stage:43,difficulty:.87,prereq:['scene:upper-change','voice:inner-voice-motion'],generatorContract:'scene.stream',judgeContract:'scene.role-change',audibleInvariant:'identité d’une voix intérieure sous densité',params:{code:'inner-change',targetRole:'inner'},frontierContract:{capability:'scene_hearing',oracle:'changed_role=inner'}}),
    unit({id:'scene:role-exchange',family:'scene',kind:'scene',group:'scene.tracking',label:'Échange des rôles',stage:44,difficulty:.89,prereq:['scene:lower-change','voice:voice-exchange'],generatorContract:'scene.stream',judgeContract:'scene.role-exchange',audibleInvariant:'matériau persistant malgré échange des rôles',params:{code:'role-exchange',targetRole:'upper'},frontierContract:{capability:'scene_hearing',oracle:'role_exchange=true'}}),
    unit({id:'scene:layer-entry-exit',family:'scene',kind:'scene',group:'scene.tracking',label:'Couche apparue ou disparue',stage:45,difficulty:.88,prereq:['scene:inner-change','texture:register-density'],generatorContract:'scene.stream',judgeContract:'scene.layer-presence',audibleInvariant:'nombre et identité des couches actives',params:{code:'layer-entry-exit',targetRole:'inner'},frontierContract:{capability:'scene_hearing',oracle:'layer_delta!=0'}}),
    unit({id:'scene:masking-continuity',family:'scene',kind:'scene',group:'scene.tracking',label:'Source maintenue sous masquage',stage:46,difficulty:.93,prereq:['scene:role-exchange','scene:layer-entry-exit'],generatorContract:'scene.stream',judgeContract:'scene.continuity',audibleInvariant:'continuité de la source cible malgré un masque croissant',params:{code:'masking-continuity',targetRole:'upper'},frontierContract:{capability:'scene_hearing',oracle:'target_unchanged_and_mask_increases'}}),

    unit({id:'timbre:pitch-attack',family:'timbre',kind:'timbre',group:'timbre.pitch-invariance',label:'Hauteur stable, attaque différente',stage:30,difficulty:.72,prereq:['timbre:instrument-family','interval:P8:asc'],generatorContract:'timbre.pitch-invariance',judgeContract:'timbre.pitch-invariance',audibleInvariant:'même hauteur malgré une enveloppe d’attaque différente',params:{code:'pitch-attack',invariantType:'absolute-pitch'},frontierContract:{capability:'timbre_pitch_invariance',oracle:'pitch_signature_equal'}}),
    unit({id:'timbre:pitch-brightness',family:'timbre',kind:'timbre',group:'timbre.pitch-invariance',label:'Intervalle stable, brillance différente',stage:31,difficulty:.76,prereq:['timbre:pitch-attack','interval:P5:harm'],generatorContract:'timbre.pitch-invariance',judgeContract:'timbre.pitch-invariance',audibleInvariant:'même intervalle sous déplacement du centre spectral',params:{code:'pitch-brightness',invariantType:'interval'},frontierContract:{capability:'timbre_pitch_invariance',oracle:'interval_signature_equal'}}),
    unit({id:'timbre:missing-fundamental',family:'timbre',kind:'timbre',group:'timbre.pitch-invariance',label:'Hauteur virtuelle sans fondamental',stage:32,difficulty:.82,prereq:['timbre:pitch-brightness','interval:P8:harm'],generatorContract:'timbre.pitch-invariance',judgeContract:'timbre.virtual-pitch',audibleInvariant:'même hauteur virtuelle avec fondamental présent ou affaibli',params:{code:'missing-fundamental',invariantType:'virtual-pitch'},frontierContract:{capability:'timbre_pitch_invariance',oracle:'virtual_pitch_equal'}}),
    unit({id:'timbre:inharmonic-carrier',family:'timbre',kind:'timbre',group:'timbre.pitch-invariance',label:'Relation stable dans un son inharmonique',stage:33,difficulty:.87,prereq:['timbre:missing-fundamental','tuning:18:0'],generatorContract:'timbre.pitch-invariance',judgeContract:'timbre.pitch-invariance',audibleInvariant:'relation de hauteur conservée sous étalement inharmonique borné',params:{code:'inharmonic-carrier',invariantType:'interval'},frontierContract:{capability:'timbre_pitch_invariance',oracle:'midi_relation_equal'}}),
    unit({id:'timbre:register-class',family:'timbre',kind:'timbre',group:'timbre.pitch-invariance',label:'Classe de hauteur malgré le registre',stage:34,difficulty:.84,prereq:['timbre:pitch-attack','interval:P8:asc'],generatorContract:'timbre.pitch-invariance',judgeContract:'timbre.pitch-class',audibleInvariant:'classe de hauteur conservée malgré octave et instrument',params:{code:'register-class',invariantType:'pitch-class'},frontierContract:{capability:'timbre_pitch_invariance',oracle:'pitch_class_equal'}}),

    unit({id:'rhythm:relational-bass-leads',family:'rhythm',kind:'rhythm',group:'rhythm.relational',label:'Basse légèrement en avant',stage:95,difficulty:.88,prereq:['rhythm:microGroove','bass:root-motion'],generatorContract:'rhythm.relational',judgeContract:'rhythm.role-offset',audibleInvariant:'avance stable de la basse relativement à la pulsation',params:{code:'bass-leads',targetRole:'bass',relation:'leads'},frontierContract:{capability:'relational_microtiming',physicalLatencyMeasured:false}}),
    unit({id:'rhythm:relational-snare-lags',family:'rhythm',kind:'rhythm',group:'rhythm.relational',label:'Caisse claire légèrement en arrière',stage:96,difficulty:.89,prereq:['rhythm:microGroove','rhythm:backbeat'],generatorContract:'rhythm.relational',judgeContract:'rhythm.role-offset',audibleInvariant:'retard stable de la caisse claire relativement à la pulsation',params:{code:'snare-lags',targetRole:'snare',relation:'lags'},frontierContract:{capability:'relational_microtiming',physicalLatencyMeasured:false}}),
    unit({id:'rhythm:relational-upper-leads',family:'rhythm',kind:'rhythm',group:'rhythm.relational',label:'Couche supérieure en avant',stage:97,difficulty:.91,prereq:['rhythm:relational-bass-leads','texture:melody-bass'],generatorContract:'rhythm.relational',judgeContract:'rhythm.role-offset',audibleInvariant:'avance de la couche supérieure relativement à la basse',params:{code:'upper-leads',targetRole:'upper',relation:'leads'},frontierContract:{capability:'relational_microtiming',physicalLatencyMeasured:false}}),
    unit({id:'rhythm:relational-tempo-scaled',family:'rhythm',kind:'rhythm',group:'rhythm.relational',label:'Décalage proportionnel au tempo',stage:98,difficulty:.94,prereq:['rhythm:relational-snare-lags','rhythm:relational-upper-leads'],generatorContract:'rhythm.relational',judgeContract:'rhythm.offset-law',audibleInvariant:'décalage relatif constant en fraction de pulsation',params:{code:'tempo-scaled',targetRole:'snare',relation:'tempo-scaled'},frontierContract:{capability:'relational_microtiming',physicalLatencyMeasured:false}}),

    unit({id:'prediction:interval-rule',family:'prediction',kind:'prediction',group:'prediction.expectation',label:'Poursuite de l’intervalle appris',stage:42,difficulty:.78,prereq:['melody:sequence','interval:M2:asc'],generatorContract:'prediction.continuation',judgeContract:'prediction.compatibility',audibleInvariant:'continuation conforme à une règle intervallique induite dans la séance',params:{code:'interval-rule'},frontierContract:{capability:'prediction_expectation',scope:SESSION_SCOPE}}),
    unit({id:'prediction:contour-rule',family:'prediction',kind:'prediction',group:'prediction.expectation',label:'Poursuite du contour appris',stage:43,difficulty:.81,prereq:['prediction:interval-rule','melody:arch'],generatorContract:'prediction.continuation',judgeContract:'prediction.compatibility',audibleInvariant:'continuation conforme à un contour induit dans la séance',params:{code:'contour-rule'},frontierContract:{capability:'prediction_expectation',scope:SESSION_SCOPE}}),
    unit({id:'prediction:cadential-rule',family:'prediction',kind:'prediction',group:'prediction.expectation',label:'Résolution de la tension apprise',stage:44,difficulty:.86,prereq:['prediction:contour-rule','progression:cadence:authentic'],generatorContract:'prediction.continuation',judgeContract:'prediction.compatibility',audibleInvariant:'continuation conforme à la tension et résolution démontrées',params:{code:'cadential-rule'},frontierContract:{capability:'prediction_expectation',scope:SESSION_SCOPE}}),
    unit({id:'prediction:microgrammar',family:'prediction',kind:'prediction',group:'prediction.expectation',label:'Continuation de la microgrammaire',stage:45,difficulty:.91,prereq:['prediction:interval-rule','prediction:contour-rule','motive:transposition'],generatorContract:'prediction.continuation',judgeContract:'prediction.compatibility',audibleInvariant:'compatibilité avec une microgrammaire locale apprise sans étiquette',params:{code:'microgrammar'},frontierContract:{capability:'prediction_expectation',scope:SESSION_SCOPE,traditionModel:false}}),

    unit({id:'voice:poly-bass-track',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Suite de la basse',stage:41,difficulty:.83,prereq:['voice:counterpoint-three-part','bass:root-motion'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.role-sequence',audibleInvariant:'séquence sémantique de la basse dans trois voix',params:{code:'poly-bass-track',voices:3,targetRole:'bass'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),
    unit({id:'voice:poly-soprano-track',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Suite du soprano',stage:42,difficulty:.84,prereq:['voice:poly-bass-track','voice:outer-motion'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.role-sequence',audibleInvariant:'séquence sémantique du soprano dans trois voix',params:{code:'poly-soprano-track',voices:3,targetRole:'soprano'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),
    unit({id:'voice:poly-alto-change',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Altération de l’alto',stage:43,difficulty:.88,prereq:['voice:poly-soprano-track','voice:inner-voice-motion'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.role-change',audibleInvariant:'localisation d’une altération dans la voix d’alto',params:{code:'poly-alto-change',voices:4,targetRole:'alto'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),
    unit({id:'voice:poly-tenor-change',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Altération du ténor',stage:44,difficulty:.89,prereq:['voice:poly-alto-change'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.role-change',audibleInvariant:'localisation d’une altération dans la voix de ténor',params:{code:'poly-tenor-change',voices:4,targetRole:'tenor'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),
    unit({id:'voice:poly-common-tone',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Voix portant la note commune',stage:45,difficulty:.90,prereq:['voice:poly-tenor-change','voice:common-tone'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.common-tone-role',audibleInvariant:'identité de la voix qui maintient la note commune',params:{code:'poly-common-tone',voices:4,targetRole:'alto'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),
    unit({id:'voice:poly-contrary-pair',family:'voice',kind:'voice',group:'voice.polyphonic-semantic',label:'Paire en mouvement contraire',stage:46,difficulty:.94,prereq:['voice:poly-common-tone','voice:contrary-motion'],generatorContract:'voice.polyphonic-semantic',judgeContract:'voice.role-pair',audibleInvariant:'paire de voix réalisant un mouvement contraire dans quatre voix',params:{code:'poly-contrary-pair',voices:4,targetRole:'soprano-bass'},frontierContract:{capability:'polyphonic_semantics',visualRequired:false}}),

    unit({id:'schema:rise-return',family:'schema',kind:'schema',group:'schema.abstract',label:'Élan puis retour',stage:44,difficulty:.82,prereq:['motive:transposition','melody:arch'],generatorContract:'schema.pattern',judgeContract:'schema.invariance',audibleInvariant:'même organisation élan-retour malgré tonalité, rythme et timbre',params:{code:'rise-return',schemaId:'rise-return'},frontierContract:{capability:'structural_schema',scope:SESSION_SCOPE,historicalAttribution:false}}),
    unit({id:'schema:descent-support',family:'schema',kind:'schema',group:'schema.abstract',label:'Descente de soutien',stage:45,difficulty:.85,prereq:['schema:rise-return','bass:root-motion'],generatorContract:'schema.pattern',judgeContract:'schema.invariance',audibleInvariant:'même descente de soutien sous surface harmonique variable',params:{code:'descent-support',schemaId:'descent-support'},frontierContract:{capability:'structural_schema',scope:SESSION_SCOPE,historicalAttribution:false}}),
    unit({id:'schema:call-balance',family:'schema',kind:'schema',group:'schema.abstract',label:'Appel puis équilibre',stage:46,difficulty:.87,prereq:['schema:rise-return','texture:call-response'],generatorContract:'schema.pattern',judgeContract:'schema.invariance',audibleInvariant:'même relation appel-réponse sous transposition et orchestration',params:{code:'call-balance',schemaId:'call-balance'},frontierContract:{capability:'structural_schema',scope:SESSION_SCOPE,historicalAttribution:false}}),
    unit({id:'schema:tension-release',family:'schema',kind:'schema',group:'schema.abstract',label:'Accumulation puis détente',stage:47,difficulty:.92,prereq:['schema:descent-support','schema:call-balance','progression:cadence:deceptive'],generatorContract:'schema.pattern',judgeContract:'schema.invariance',audibleInvariant:'même trajectoire tension-détente malgré plusieurs surfaces',params:{code:'tension-release',schemaId:'tension-release'},frontierContract:{capability:'structural_schema',scope:SESSION_SCOPE,historicalAttribution:false}})
  ]);

  const GENERATOR_CONTRACTS=deepFreeze({
    'scene.stream':{capability:'scene_hearing',build:'buildSceneSpec'},
    'timbre.pitch-invariance':{capability:'timbre_pitch_invariance',build:'buildTimbrePitchSpec'},
    'rhythm.relational':{capability:'relational_microtiming',build:'buildRelationalRhythmSpec'},
    'prediction.continuation':{capability:'prediction_expectation',build:'buildPredictionSpec'},
    'voice.polyphonic-semantic':{capability:'polyphonic_semantics',build:'buildPolyphonicSpec'},
    'schema.pattern':{capability:'structural_schema',build:'buildSchemaSpec'}
  });
  const JUDGE_CONTRACTS=deepFreeze({
    'scene.role-change':{mode:'scene'},'scene.role-exchange':{mode:'scene'},'scene.layer-presence':{mode:'scene'},'scene.continuity':{mode:'scene'},
    'timbre.pitch-invariance':{mode:'invariance'},'timbre.virtual-pitch':{mode:'invariance'},'timbre.pitch-class':{mode:'invariance'},
    'rhythm.role-offset':{mode:'timing'},'rhythm.offset-law':{mode:'timing'},'prediction.compatibility':{mode:'expectation'},
    'voice.role-sequence':{mode:'polyphonic'},'voice.role-change':{mode:'polyphonic'},'voice.common-tone-role':{mode:'polyphonic'},'voice.role-pair':{mode:'polyphonic'},
    'schema.invariance':{mode:'schema'}
  });
  const UNIT_BY_ID=deepFreeze(Object.fromEntries(UNITS.map(row=>[row.id,row])));

  function sceneVoices(root,variant=0){const shift=variant%3-1;return{
    lower:[root-12,root-10,root-8,root-7].map(n=>n+shift),
    inner:[root+4,root+5,root+7,root+5].map(n=>n-shift),
    upper:[root+12,root+14,root+16,root+17].map(n=>n+shift)
  }}
  function addVoice(events,notes,role,start,timbre,velocity=.66){for(let i=0;i<notes.length;i++)events.push(event(notes[i],start+i*.56,.46,i===0?velocity+.1:velocity,{role,timbre,articulation:'legato'}))}
  function buildSceneSpec(unit,context,random){const code=unit.params.code,variant=Math.floor(random()*100000),root=choose(random,[47,48,49]),upperCarrier=choose(random,['clarinet','strings','epiano']),innerCarrier=choose(random,['epiano','fmKeys','organ']),lowerCarrier=choose(random,['bass','synthBass','acidBass']),A=sceneVoices(root,variant),B={lower:[...A.lower],inner:[...A.inner],upper:[...A.upper]},events=[],gap=3.25,delta=choose(random,[-2,-1,1,2]);let changedRole='',layerDelta=0,roleExchange=false,maskIncrease=false;context.root=root;context.timbre=upperCarrier;
    if(code==='upper-change'){B.upper[2]+=delta;changedRole='upper'}
    else if(code==='lower-change'){B.lower[2]+=delta;changedRole='lower'}
    else if(code==='inner-change'){B.inner[1]+=delta;changedRole='inner'}
    else if(code==='role-exchange'){[B.lower,B.upper]=[B.upper.map(n=>n-24),B.lower.map(n=>n+24)];roleExchange=true;changedRole='lower,upper'}
    else if(code==='layer-entry-exit'){if(random()<.5){B.inner=[];layerDelta=-1}else{A.inner=[];layerDelta=1}changedRole='inner'}
    addVoice(events,A.lower,'lower',0,lowerCarrier,.68);addVoice(events,A.inner,'inner',0,innerCarrier,.55);addVoice(events,A.upper,'upper',0,upperCarrier,.70);
    addVoice(events,B.lower,'lower',gap,lowerCarrier,.68);addVoice(events,B.inner,'inner',gap,innerCarrier,.55);addVoice(events,B.upper,'upper',gap,upperCarrier,.70);
    if(code==='masking-continuity'){maskIncrease=true;for(let i=0;i<8;i++){events.push(event([],gap+i*.28,.10,.30+i*.06,{type:'percussion',instrument:i%2?'hatClosed':'snare',role:'mask'}));events.push(event([root-1,root+3,root+6],gap+i*.28,.20,.24+i*.04,{role:'mask',timbre:'synthPad',articulation:'staccato'}))}}
    context.presentation='scene-hearing';context.textureId=code;context.roles=['lower','inner','upper',...(maskIncrease?['mask']:[])];
    return{kind:'scene',textureId:code,roles:context.roles,timbre:context.timbre,score:score(events,68+Math.floor(random()*25)),sceneContract:{schema:'earforge.scene_trial.v1',phaseBoundaryTicks:Math.round(gap*PPQ),targetRole:unit.params.targetRole,changedRole,layerDelta,roleExchange,maskIncrease,sourceContinuity:code==='masking-continuity',visualRequired:false},seed:variant}
  }

  function addMotif(events,root,start,timbre,profile,pattern=[0,2,4,7],role='target'){for(let i=0;i<pattern.length;i++)events.push(event(root+pattern[i],start+i*.52,.42,i===0?.78:.66,{role,timbre,articulation:i===0?'accent':'legato',spectralProfile:profile}))}
  function buildTimbrePitchSpec(unit,context,random){const code=unit.params.code,root=choose(random,[60,61,62]),events=[],gap=2.7,carriers=shuffle(random,['piano','flute','strings','digitalPluck','vibraphone','fmKeys']),a=carriers[0],b=carriers[1],contract={schema:'earforge.timbre_pitch_trial.v1',invariantType:unit.params.invariantType,carrierA:a,carrierB:b,pitchSignature:null,visualRequired:false};
    if(code==='pitch-attack'){addMotif(events,root,0,a,'hard-attack',[0,0,2,0],'variant-a');addMotif(events,root,gap,b,'soft-attack',[0,0,2,0],'variant-b');contract.pitchSignature=[root,root,root+2,root]}
    else if(code==='pitch-brightness'){addMotif(events,root,0,a,'dark',[0,7,0,7],'variant-a');addMotif(events,root,gap,b,'bright',[0,7,0,7],'variant-b');contract.pitchSignature=[0,7,0,7]}
    else if(code==='missing-fundamental'){addMotif(events,root,0,a,'harmonic',[0,0,7,0],'variant-a');addMotif(events,root,gap,b,'missing-fundamental',[0,0,7,0],'variant-b');contract.pitchSignature=[root,root,root+7,root];contract.virtualPitch=true}
    else if(code==='inharmonic-carrier'){addMotif(events,root,0,a,'harmonic',[0,5,9,5],'variant-a');addMotif(events,root,gap,b,'inharmonic',[0,5,9,5],'variant-b');contract.pitchSignature=[0,5,9,5];contract.inharmonicSpread='bounded'}
    else{addMotif(events,root,0,a,'harmonic',[0,4,7,0],'variant-a');addMotif(events,root+12,gap,b,'bright',[0,4,7,0],'variant-b');contract.pitchSignature=[0,4,7,0];contract.pitchClassInvariant=true}
    context.root=root;context.timbre=a;context.presentation='timbre-pitch-invariance';context.textureId=code;context.roles=['variant-a','variant-b'];return{kind:'timbre',textureId:code,roles:context.roles,timbre:a,score:score(events,64+Math.floor(random()*36)),timbrePitchContract:contract,seed:Math.floor(random()*2**31)}
  }

  function buildRelationalRhythmSpec(unit,context,random){const code=unit.params.code,tempo=choose(random,[60,72,84,96,108,120]),offsetFraction=choose(random,[.035,.045,.055,.065]),offset=Math.round(PPQ*offsetFraction),events=[],bass=[],upper=[];for(let beat=1;beat<=8;beat++){events.push(['woodblock',beat*PPQ,beat===1?.65:.42,0,'context']);bass.push(['bassPulse',beat*PPQ,.72,code==='bass-leads'?-offset:0,'context',36+(beat%4===0?5:0)]);upper.push(['chordPulse',beat*PPQ,.55,code==='upper-leads'?-offset:0,'context',48+(beat%4===0?5:0)]);if(beat%2===0)events.push(['snare',beat*PPQ,.74,(code==='snare-lags'||code==='tempo-scaled')?offset:0,'snare'])}const targetRole=unit.params.targetRole,relation=unit.params.relation;context.presentation='relational-microtiming';context.mode=code;context.meter='4/4';context.roles=['pulse','bass','upper','snare'];return{kind:'rhythm',axis:'relational-microtiming',events,layers:[bass,upper],rests:[],ppq:PPQ,stepTicks:PPQ/2,durationTicks:10*PPQ,tempoUnitTicks:PPQ,countInTicks:0,countInGapTicks:0,tempo,swing:0,kit:'dry',contextRoot:48,relationContract:{schema:'earforge.relational_timing.v1',targetRole,relation,offsetTicks:offset,offsetFraction,tempoScaled:code==='tempo-scaled',physicalLatencyMeasured:false,visualRequired:false},seed:Math.floor(random()*2**31)}
  }

  function buildPredictionSpec(unit,context,random){const code=unit.params.code,root=62,events=[],timbres=shuffle(random,['piano','clarinet','epiano','digitalPluck']),exampleGap=2.55;let examples=[],candidate=[],rule='';context.root=root;context.timbre=timbres[0];
    if(code==='interval-rule'){const step=choose(random,[1,2,3,5]);examples=[[0,step,2*step,3*step],[2,2+step,2+2*step,2+3*step]];candidate=[4,4+step,4+2*step,4+3*step];rule=`interval:${step}`}
    else if(code==='contour-rule'){examples=[[0,2,5,2,0],[3,5,8,5,3]];candidate=[-2,0,3,0,-2];rule='contour:rise-peak-return'}
    else if(code==='cadential-rule'){examples=[[0,5,7,0],[2,5,7,0]];candidate=[4,5,7,0];rule='tension:dominant-to-tonic'}
    else{const motif=choose(random,[[0,2,1,3],[0,3,1,4],[0,2,4,1]]);examples=[motif,motif.map(x=>x+5)];candidate=motif.map(x=>x-3);rule=`microgrammar:${motif.map((x,i)=>i?x-motif[i-1]:0).join(',')}`}
    for(let k=0;k<examples.length;k++)for(let i=0;i<examples[k].length;i++)events.push(event(root+examples[k][i],k*exampleGap+i*.42,.34,i===0?.80:.64,{role:`example-${k+1}`,timbre:timbres[k],articulation:'legato'}));const start=examples.length*exampleGap+.45;for(let i=0;i<candidate.length;i++)events.push(event(root+candidate[i],start+i*.42,.34,i===0?.86:.68,{role:'candidate',timbre:timbres[2],articulation:'legato'}));context.presentation='induced-expectation';context.textureId=code;context.roles=['example-1','example-2','candidate'];return{kind:'prediction',textureId:code,roles:context.roles,timbre:timbres[0],score:score(events,66+Math.floor(random()*30)),expectationContract:{schema:'earforge.induced_expectation.v1',scope:SESSION_SCOPE,traditionModel:false,rule,examples,candidate,compatible:true,textLeakage:false,visualRequired:false},seed:Math.floor(random()*2**31)}
  }

  const VOICE_RANGES={bass:-12,tenor:0,alto:7,soprano:14};
  function polyLines(root,voices,variant){const roles=voices===3?['bass','alto','soprano']:['bass','tenor','alto','soprano'],templates={bass:[0,2,4,5],tenor:[4,5,7,5],alto:[7,9,8,9],soprano:[12,11,14,12]},lines={};for(const role of roles)lines[role]=templates[role].map(n=>root+VOICE_RANGES[role]+n+(variant%2&&role==='tenor'?1:0));return{roles,lines}}
  function buildPolyphonicSpec(unit,context,random){const p=unit.params,variant=Math.floor(random()*1000),root=choose(random,[47,48,49]),{roles,lines}=polyLines(root,p.voices,variant),events=[];context.root=root;context.timbre='flute';let changedRole='',commonToneRole='',contraryPair=[];if(p.code==='poly-alto-change'){lines.alto[2]+=choose(random,[-1,1]);changedRole='alto'}else if(p.code==='poly-tenor-change'){lines.tenor[1]+=choose(random,[-1,1]);changedRole='tenor'}else if(p.code==='poly-common-tone'){lines.alto[1]=lines.alto[0];commonToneRole='alto'}else if(p.code==='poly-contrary-pair'){lines.bass=[root-12,root-14,root-16,root-17];lines.soprano=[root+26,root+28,root+30,root+31];contraryPair=['bass','soprano']}
    const timbre={bass:choose(random,['bass','synthBass']),tenor:choose(random,['epiano','organ']),alto:choose(random,['strings','fmKeys']),soprano:'flute'};for(const role of roles)for(let i=0;i<lines[role].length;i++)events.push(event(lines[role][i],i*.68,.58,i===0?.76:.62,{role,timbre:timbre[role],articulation:'legato'}));context.presentation='polyphonic-semantics';context.textureId=p.code;context.roles=roles;return{kind:'voice',textureId:p.code,roles,timbre:context.timbre,score:score(events,58+Math.floor(random()*27)),polyphonicContract:{schema:'earforge.polyphonic_semantics.v1',voiceCount:roles.length,roles,targetRole:p.targetRole,roleSequences:Object.fromEntries(roles.map(role=>[role,lines[role].map(n=>n-root)])),changedRole,commonToneRole,contraryPair,semanticSequenceRequired:true,flatteningForbidden:true,visualRequired:false},seed:variant}
  }

  function buildSchemaSpec(unit,context,random){const code=unit.params.code,root=choose(random,[60,61,62]),events=[],timbres=shuffle(random,['piano','epiano','organ','fmKeys']),surfaceShift=choose(random,[-5,-2,0,3,5,7]),tempo=choose(random,[60,72,84,96,108]);let melody=[],bass=[],schemaId=unit.params.schemaId;context.root=root;context.timbre=timbres[0];
    if(code==='rise-return'){melody=[0,2,5,7,5,2,0];bass=[0,0,5,5,0,0,0]}
    else if(code==='descent-support'){melody=[7,9,7,5,4,2,0];bass=[7,5,4,2,0,-2,-5]}
    else if(code==='call-balance'){melody=[0,2,5,2,null,5,4,2,0];bass=[0,0,0,0,null,5,5,0,0]}
    else{melody=[0,2,4,5,7,8,7,5,4,2,0];bass=[0,0,2,2,4,4,5,5,7,7,0]}
    for(let i=0;i<melody.length;i++){if(melody[i]==null)continue;events.push(event(root+surfaceShift+melody[i],i*.46,.37,i===0?.82:.66,{role:'schema-upper',timbre:timbres[0],articulation:'legato'}));events.push(event(root-12+surfaceShift+bass[i],i*.46,.42,i===0?.72:.56,{role:'schema-lower',timbre:timbres[1],articulation:'tenuto'}))}context.presentation='abstract-schema';context.textureId=schemaId;context.roles=['schema-upper','schema-lower'];return{kind:'schema',textureId:schemaId,roles:context.roles,timbre:timbres[0],score:score(events,tempo),schemaContract:{schema:'earforge.abstract_schema.v1',schemaId,scope:SESSION_SCOPE,historicalAttribution:false,traditionModel:false,surfaceAxes:{transposition:surfaceShift,tempo,timbres:timbres.slice(0,2)},invariant:'relative-role-trajectory',visualRequired:false},seed:Math.floor(random()*2**31)}
  }

  function buildQuestionSpec(unit,context,random){const contract=GENERATOR_CONTRACTS[unit?.generatorContract];if(!contract)return null;const builders={'scene.stream':buildSceneSpec,'timbre.pitch-invariance':buildTimbrePitchSpec,'rhythm.relational':buildRelationalRhythmSpec,'prediction.continuation':buildPredictionSpec,'voice.polyphonic-semantic':buildPolyphonicSpec,'schema.pattern':buildSchemaSpec};return builders[unit.generatorContract](unit,context,random)}

  function roleSequences(input){const declared=input?.roleSequences||input?.polyphonicContract?.roleSequences||input?.sceneContract?.roleSequences;if(declared&&typeof declared==='object'&&!Array.isArray(declared)){const roles={};for(const [role,values] of Object.entries(declared))roles[String(role)]=(values||[]).map(Number).filter(Number.isFinite);return roles}const events=input?.events||input?.score?.events||[],roles={};for(const row of events){if(row.type==='percussion'||row.instrument)continue;const role=String(row.role||'target'),notes=(row.notes||[]).map(Number).filter(Number.isFinite);if(!roles[role])roles[role]=[];roles[role].push(...notes)}return roles}
  function normalizeRelative(values){if(!values.length)return[];const first=values[0];return values.map(value=>Math.round((Number(value)-first)*1000)/1000)}
  function sequenceSimilarity(a,b,{transpose=true}={}){const A=(a||[]).map(Number).filter(Number.isFinite),B=(b||[]).map(Number).filter(Number.isFinite);if(!A.length&&!B.length)return 1;if(!A.length||!B.length)return 0;const X=transpose?normalizeRelative(A):A,Y=transpose?normalizeRelative(B):B,n=Math.max(X.length,Y.length),m=Math.min(X.length,Y.length);let cost=Math.abs(X.length-Y.length);for(let i=0;i<m;i++)cost+=Math.min(12,Math.abs(X[i]-Y[i]))/12;return clamp(1-cost/Math.max(1,n),0,1)}
  function polyphonicSemanticScore(reference,response,{allowRoleTransposition=true}={}){const A=roleSequences(reference),B=roleSequences(response),roles=unique([...Object.keys(A),...Object.keys(B)]).sort(),perRole={};let total=0;for(const role of roles){const value=sequenceSimilarity(A[role]||[],B[role]||[],{transpose:allowRoleTransposition});perRole[role]={score:value,referenceLength:(A[role]||[]).length,responseLength:(B[role]||[]).length};total+=value}const scoreValue=roles.length?total/roles.length:0,flatA=Object.values(A).flat(),flatB=Object.values(B).flat(),flattenedScore=sequenceSimilarity(flatA,flatB,{transpose:allowRoleTransposition});return{schema:'earforge.polyphonic_score.v1',valid:roles.length>0,score:scoreValue,flattenedScore,rolePenalty:Math.max(0,flattenedScore-scoreValue),roles,perRole,flatteningForbidden:true,visualRequired:false}}

  function analyzeSceneTrial(reference,candidate,{targetRole='upper'}={}){const A=roleSequences(reference),B=roleSequences(candidate),roles=unique([...Object.keys(A),...Object.keys(B)]).sort(),changedRoles=[],appeared=[],disappeared=[];for(const role of roles){if(!A[role]?.length&&B[role]?.length)appeared.push(role);else if(A[role]?.length&&!B[role]?.length)disappeared.push(role);else if(sequenceSimilarity(A[role],B[role],{transpose:false})<.999)changedRoles.push(role)}const targetSimilarity=sequenceSimilarity(A[targetRole]||[],B[targetRole]||[],{transpose:false}),maskA=(A.mask||[]).length,maskB=(B.mask||[]).length;return{schema:'earforge.scene_analysis.v1',roles,changedRoles,appeared,disappeared,targetRole,targetContinuity:targetSimilarity,maskIncrease:maskB>maskA,roleExchange:changedRoles.includes('upper')&&changedRoles.includes('lower')&&sequenceSimilarity(A.upper||[],B.lower||[])>.9&&sequenceSimilarity(A.lower||[],B.upper||[])>.9,visualRequired:false}}

  function layerRows(input){if(Array.isArray(input))return input.map(row=>({role:String(row.role||''),times:(row.times||[]).map(Number).filter(Number.isFinite)})).filter(row=>row.role&&row.times.length);return Object.entries(input||{}).map(([role,times])=>({role,times:(times||[]).map(Number).filter(Number.isFinite)})).filter(row=>row.times.length)}
  function relationalTimingProfile(input,{referenceRole=null,tempoBpm=72,alignedToleranceMs=4}={}){const rows=layerRows(input);if(rows.length<2)return{schema:'earforge.relational_timing_profile.v1',valid:false,roles:rows.map(x=>x.role),physicalLatencyMeasured:false};const ref=rows.find(x=>x.role===referenceRole)||rows[0],offsets={};for(const row of rows){const n=Math.min(ref.times.length,row.times.length),d=[];for(let i=0;i<n;i++)d.push(row.times[i]-ref.times[i]);const offset=median(d);offsets[row.role]={n,medianOffsetMs:offset,relation:Math.abs(offset)<=alignedToleranceMs?'aligned':offset<0?'leads':'lags',beatFraction:offset/(60000/clamp(tempoBpm,20,300))}}return{schema:'earforge.relational_timing_profile.v1',valid:true,referenceRole:ref.role,tempoBpm:clamp(tempoBpm,20,300),offsets,globalTranslationInvariant:true,physicalLatencyMeasured:false,visualRequired:false}}

  function normalizedPattern(pattern){const xs=(pattern||[]).map(Number).filter(Number.isFinite).map(Math.abs),sum=xs.reduce((a,b)=>a+b,0);return sum?xs.map(x=>x/sum):[]}
  function patternDistance(a,b){const A=normalizedPattern(a),B=normalizedPattern(b),n=Math.max(A.length,B.length);if(!n)return Infinity;let d=0;for(let i=0;i<n;i++)d+=Math.abs(Number(A[i]||0)-Number(B[i]||0));return d/n}
  function inducedPrototypeModel(examples,{candidates=[]}={}){const rows=(examples||[]).map(normalizedPattern).filter(x=>x.length),length=rows.length?Math.min(...rows.map(x=>x.length)):0;if(!length)return{schema:'earforge.induced_prototype.v1',status:'INSUFFICIENT',scope:SESSION_SCOPE,traditionModel:false};const center=Array.from({length},(_,i)=>mean(rows.map(row=>row[i]))),total=center.reduce((a,b)=>a+b,0),normalizedCenter=center.map(x=>x/Math.max(1e-12,total)),scored=(candidates||[]).map((pattern,index)=>({index,distance:patternDistance(normalizedCenter,pattern)})).sort((a,b)=>a.distance-b.distance);return{schema:'earforge.induced_prototype.v1',status:'READY',scope:SESSION_SCOPE,traditionModel:false,n:rows.length,center:normalizedCenter,dispersion:mean(rows.map(row=>patternDistance(normalizedCenter,row))),candidates:scored,visualRequired:false}}

  function intervals(sequence){const s=(sequence||[]).map(Number).filter(Number.isFinite);return s.slice(1).map((value,index)=>value-s[index])}
  function inducedExpectationModel(examples,{candidates=[]}={}){const rows=(examples||[]).map(intervals).filter(x=>x.length);if(!rows.length)return{schema:'earforge.induced_expectation_model.v1',status:'INSUFFICIENT',scope:SESSION_SCOPE,traditionModel:false};const counts=new Map();for(const row of rows)for(const value of row){const key=Math.round(value*1000)/1000;counts.set(key,(counts.get(key)||0)+1)}const total=[...counts.values()].reduce((a,b)=>a+b,0),probabilities=Object.fromEntries([...counts].sort((a,b)=>a[0]-b[0]).map(([key,count])=>[key,count/total]));const scoreCandidate=sequence=>{const xs=intervals(sequence);if(!xs.length)return 0;let log=0;for(const value of xs)log+=Math.log((probabilities[Math.round(value*1000)/1000]||0)+1/(total+counts.size+4));return Math.exp(log/xs.length)};const scored=(candidates||[]).map((sequence,index)=>({index,score:scoreCandidate(sequence)})).sort((a,b)=>b.score-a.score);return{schema:'earforge.induced_expectation_model.v1',status:'READY',scope:SESSION_SCOPE,traditionModel:false,n:rows.length,probabilities,candidates:scored,visualRequired:false}}

  function contextKey(row){const source=row.context&&typeof row.context==='object'?row.context:row,parts=[];for(const key of ['timbre','register','durationBand','harmonicContext','direction','intervalClass','density'])if(source[key]!=null&&source[key]!=='')parts.push(`${key}:${source[key]}`);return parts.join('|')||'global'}
  function thresholdValue(row){let value=Number(row.thresholdCents??row.estimateCents??row.cents);if(!Number.isFinite(value)&&typeof row.unitId==='string'){const m=/^tuning:([0-9.]+):/.exec(row.unitId);if(m)value=Number(m[1])}return value}
  function hierarchicalIntonationMap(rows,{priorStrength=8,defaultThresholdCents=18,minCents=1,maxCents=100}={}){const clean=[];for(const row of rows||[]){const value=thresholdValue(row),n=Math.max(1,Math.round(Number(row.n)||1));if(Number.isFinite(value)&&value>0)clean.push({value:clamp(value,minCents,maxCents),n,key:contextKey(row),context:row.context||null})}if(!clean.length)return{schema:'earforge.intonation_map.v1',status:'ZERO_DATA',authoritative:false,totalN:0,global:{estimateCents:clamp(defaultThresholdCents,minCents,maxCents),confidence:0},contexts:[],model:'hierarchical_log_threshold_shrinkage'};let sum=0,totalN=0;for(const row of clean){sum+=Math.log(row.value)*row.n;totalN+=row.n}const globalLog=sum/totalN,global=Math.exp(globalLog),groups=new Map();for(const row of clean){const g=groups.get(row.key)||{key:row.key,n:0,sum:0};g.n+=row.n;g.sum+=Math.log(row.value)*row.n;groups.set(row.key,g)}const contexts=[...groups.values()].map(g=>{const localLog=g.sum/g.n,weight=g.n/(g.n+Math.max(1,priorStrength)),estimate=Math.exp((1-weight)*globalLog+weight*localLog);return{contextKey:g.key,n:g.n,estimateCents:clamp(estimate,minCents,maxCents),rawEstimateCents:clamp(Math.exp(localLog),minCents,maxCents),shrinkageWeight:weight,correctionRatio:estimate/global,confidence:weight,authoritative:totalN>=96&&g.n>=16}}).sort((a,b)=>b.n-a.n||a.contextKey.localeCompare(b.contextKey));return{schema:'earforge.intonation_map.v1',status:'READY',authoritative:totalN>=96,totalN,global:{estimateCents:clamp(global,minCents,maxCents),confidence:totalN/(totalN+priorStrength)},contexts,model:'hierarchical_log_threshold_shrinkage',visualRequired:false}}

  function memoryOutcome(row){if(Number.isFinite(Number(row.score)))return clamp(row.score,0,1);return row.correct===true?1:row.correct===false?0:null}
  function hierarchicalMemoryCapacityProfile(rows,{priorStrength=10}={}){const clean=[];for(const row of rows||[]){const y=memoryOutcome(row);if(y==null)continue;clean.push({y,length:Math.max(1,Math.round(Number(row.sequenceLength??row.length??row.reference?.length)||1)),delayBand:Number(row.delayMs)>86400000?'day+':Number(row.delayMs)>600000?'minutes+':'immediate',interference:String(row.interference||'none'),transposed:Boolean(row.transposed??Number(row.transpose)),timbreChanged:Boolean(row.timbreChanged),structuralTransfer:Boolean(row.structuralTransfer)})}const globalMean=(clean.reduce((a,row)=>a+row.y,0)+1.5)/(clean.length+3);if(!clean.length)return{schema:'earforge.memory_capacity_profile.v1',status:'ZERO_DATA',authoritative:false,n:0,global:globalMean,axes:{},capacityEvents:null,masteryMutation:false};const dimensions=['length','delayBand','interference','transposed','timbreChanged','structuralTransfer'],axes={};for(const dimension of dimensions){const groups=new Map();for(const row of clean){const key=String(row[dimension]),g=groups.get(key)||{n:0,sum:0};g.n++;g.sum+=row.y;groups.set(key,g)}axes[dimension]=[...groups].map(([value,g])=>{const weight=g.n/(g.n+priorStrength),raw=(g.sum+1)/(g.n+2),estimate=(1-weight)*globalMean+weight*raw;return{value,n:g.n,raw,estimate,shrinkageWeight:weight,confidence:weight}}).sort((a,b)=>String(a.value).localeCompare(String(b.value)))}const qualified=axes.length.filter(row=>row.n>=3&&row.estimate>=.7).map(row=>Number(row.value)).filter(Number.isFinite);return{schema:'earforge.memory_capacity_profile.v1',status:'READY',authoritative:clean.length>=64,n:clean.length,global:globalMean,axes,capacityEvents:qualified.length?Math.max(...qualified):null,masteryMutation:false,visualRequired:false}}

  function transferAxisMatrix(rows,{priorAlpha=1.2,priorBeta=1.8}={}){const groups=new Map();for(const row of rows||[]){const correct=row.correct===true?1:row.correct===false?0:Number.isFinite(Number(row.score))?clamp(row.score,0,1):null;if(correct==null)continue;const axis=String(row.axis||row.contextAxis||'unknown'),value=String(row.value??row.contextValue??'unknown'),key=`${axis}:${value}`,g=groups.get(key)||{axis,value,n:0,sum:0};g.n++;g.sum+=correct;groups.set(key,g)}const cells=[...groups.values()].map(g=>{const estimate=(g.sum+priorAlpha)/(g.n+priorAlpha+priorBeta),confidence=g.n/(g.n+8);return{...g,estimate,confidence,evidenceClass:g.n>=12?'QUALIFIED':g.n>=4?'PROVISIONAL':'SPARSE'}}).sort((a,b)=>a.estimate-b.estimate||b.n-a.n),weakest=cells[0]||null;return{schema:'earforge.transfer_axis_matrix.v1',status:cells.length?'READY':'ZERO_DATA',cells,weakestAxis:weakest?{axis:weakest.axis,value:weakest.value,estimate:weakest.estimate,n:weakest.n}:null,masteryMutation:false,authoritative:cells.length>0&&cells.every(x=>x.n>=12),visualRequired:false}}


  function normalInv(p){
   p=clamp(p,1e-9,1-1e-9);const a=[-39.6968302866538,220.946098424521,-275.928510446969,138.357751867269,-30.6647980661472,2.50662827745924],b=[-54.4760987982241,161.585836858041,-155.698979859887,66.8013118877197,-13.2806815528857],c=[-.00778489400243029,-.322396458041136,-2.40075827716184,-2.54973253934373,4.37466414146497,2.93816398269878],d=[.00778469570904146,.32246712907004,2.445134137143,3.75440866190742],pl=.02425,ph=1-pl;let q,r;if(p<pl){q=Math.sqrt(-2*Math.log(p));return(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}if(p>ph){q=Math.sqrt(-2*Math.log(1-p));return-(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}q=p-.5;r=q*q;return(((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)
  }
  function bernoulliValue(row){if(row?.correct===true)return 1;if(row?.correct===false)return 0;const v=Number(row?.score);return Number.isFinite(v)?clamp(v,0,1):null}
  function betaCell(rows,{priorAlpha=1.2,priorBeta=1.8}={}){let sum=0,n=0;for(const row of rows||[]){const y=bernoulliValue(row);if(y==null)continue;sum+=y;n++}const alpha=priorAlpha+sum,beta=priorBeta+n-sum,total=alpha+beta,estimate=alpha/total,variance=alpha*beta/(total*total*(total+1));return{n,sum,alpha,beta,estimate,variance,se:Math.sqrt(variance)}}
  function signalDetectionProfile(rows,{minSignal=16,minNoise=16}={}){let signal=0,noise=0,hits=0,falseAlarms=0;for(const row of rows||[]){const present=Boolean(row?.targetPresent??row?.signalPresent??row?.mutationPresent),yes=Boolean(row?.responsePresent??row?.responseChanged??row?.yes);if(present){signal++;if(yes)hits++}else{noise++;if(yes)falseAlarms++}}const hitRate=(hits+.5)/(signal+1),falseAlarmRate=(falseAlarms+.5)/(noise+1),zH=normalInv(hitRate),zF=normalInv(falseAlarmRate),dPrime=zH-zF,criterion=-.5*(zH+zF),authoritative=signal>=minSignal&&noise>=minNoise;return{schema:'earforge.signal_detection.v1',status:signal&&noise?'READY':'INSUFFICIENT',signalTrials:signal,noiseTrials:noise,hits,falseAlarms,hitRate,falseAlarmRate,dPrime,criterion,authoritative,masteryMutation:false,visualRequired:false}}
  function transferGradient(rows,{priorAlpha=1.2,priorBeta=1.8,minPerCell=12}={}){const groups=new Map();for(const row of rows||[]){const axis=String(row?.axis||row?.contextAxis||'unknown'),condition=String(row?.condition||row?.novelty||(row?.novel===true?'novel':'known')).toLowerCase();if(!['known','novel'].includes(condition))continue;const key=`${axis}:${condition}`;(groups.get(key)||groups.set(key,[]).get(key)).push(row)}const axes=[...new Set([...groups.keys()].map(k=>k.slice(0,k.lastIndexOf(':'))))],cells=[],gradients=[];for(const axis of axes){const known=betaCell(groups.get(`${axis}:known`)||[],{priorAlpha,priorBeta}),novel=betaCell(groups.get(`${axis}:novel`)||[],{priorAlpha,priorBeta}),cost=known.estimate-novel.estimate,se=Math.sqrt(known.variance+novel.variance),ci95=[cost-1.96*se,cost+1.96*se],authoritative=known.n>=minPerCell&&novel.n>=minPerCell;cells.push({axis,condition:'known',...known},{axis,condition:'novel',...novel});gradients.push({axis,known:known.estimate,novel:novel.estimate,cost,se,ci95,knownN:known.n,novelN:novel.n,authoritative})}gradients.sort((a,b)=>b.cost-a.cost);return{schema:'earforge.transfer_gradient.v1',status:gradients.length?'READY':'ZERO_DATA',cells,gradients,worst:gradients[0]||null,authoritative:gradients.length>0&&gradients.every(x=>x.authoritative),masteryMutation:false,visualRequired:false}}
  function weightedLinear(points){let sw=0,sx=0,sy=0,sxx=0,sxy=0;for(const p of points){const w=Math.max(1,Number(p.w)||1),x=Number(p.x),y=Number(p.y);if(!Number.isFinite(x)||!Number.isFinite(y))continue;sw+=w;sx+=w*x;sy+=w*y;sxx+=w*x*x;sxy+=w*x*y}const den=sw*sxx-sx*sx;if(sw<2||Math.abs(den)<1e-12)return{slope:0,intercept:sw?sy/sw:0};return{slope:(sw*sxy-sx*sy)/den,intercept:(sy*sxx-sx*sxy)/den}}
  function adaptiveSceneThreshold(rows,{targetDPrime=1.35,minTrials=32}={}){const levels=new Map();for(const row of rows||[]){const x=Number(row?.levelDb??row?.targetLevelDb??row?.snrDb);if(!Number.isFinite(x))continue;(levels.get(x)||levels.set(x,[]).get(x)).push(row)}const points=[];for(const [level,group] of levels){const s=signalDetectionProfile(group,{minSignal:1,minNoise:1});if(s.signalTrials&&s.noiseTrials)points.push({x:level,y:s.dPrime,w:s.signalTrials+s.noiseTrials,dPrime:s.dPrime,criterion:s.criterion,n:s.signalTrials+s.noiseTrials})}points.sort((a,b)=>a.x-b.x);const fit=weightedLinear(points),slope=Math.max(.01,fit.slope),threshold=(targetDPrime-fit.intercept)/slope,total=points.reduce((a,b)=>a+b.n,0),authoritative=total>=minTrials&&points.length>=3&&fit.slope>0;return{schema:'earforge.scene_threshold.v1',status:points.length>=2?'READY':'INSUFFICIENT',targetDPrime,thresholdDb:Number.isFinite(threshold)?threshold:null,slope,intercept:fit.intercept,points,trialCount:total,authoritative,masteryMutation:false,visualRequired:false}}
  function logisticFit(rows,xKey,yKey){let b0=0,b1=.08;for(let iter=0;iter<40;iter++){let g0=0,g1=0,h00=.002,h01=0,h11=.002;for(const row of rows){const x=Number(row[xKey]),y=Boolean(row[yKey])?1:0;if(!Number.isFinite(x))continue;const z=clamp(b0+b1*x,-30,30),p=1/(1+Math.exp(-z)),w=Math.max(1e-6,p*(1-p)),e=y-p;g0+=e;g1+=e*x;h00+=w;h01+=w*x;h11+=w*x*x}const det=h00*h11-h01*h01;if(Math.abs(det)<1e-12)break;const d0=(g0*h11-g1*h01)/det,d1=(g1*h00-g0*h01)/det;b0+=d0;b1+=d1;if(Math.abs(d0)+Math.abs(d1)<1e-8)break}return{intercept:b0,slope:b1}}
  function percentile(xs,p){const a=[...(xs||[])].filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*clamp(p,0,1),lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(i-lo)}
  function bootstrapIntonation(group,reps,seed){let x=hash32(seed)||1;const rand=()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/4294967296},pse=[],jnd=[],t75=[];for(let r=0;r<reps;r++){const sample=Array.from({length:group.length},()=>group[Math.floor(rand()*group.length)]),fit=logisticFit(sample,'offset','higher');if(!(fit.slope>1e-7))continue;const a=-fit.intercept/fit.slope,b=Math.log(3)/fit.slope,c=(Math.log(3)-fit.intercept)/fit.slope;if([a,b,c].every(Number.isFinite)){pse.push(a);jnd.push(b);t75.push(c)}}return{valid:pse.length,reps,pseCi95:[percentile(pse,.025),percentile(pse,.975)],jndCi95:[percentile(jnd,.025),percentile(jnd,.975)],threshold75Ci95:[percentile(t75,.025),percentile(t75,.975)]}}
  function contextualIntonationPseJnd(rows,{minTrials=48,minLevels=7,minClass=8,bootstrapReps=200}={}){const groups=new Map();for(const row of rows||[]){const key=String(row?.contextKey||contextKey(row)),x=Number(row?.offsetCents??row?.cents),y=row?.responseHigher??row?.higher;if(!Number.isFinite(x)||typeof y!=='boolean')continue;(groups.get(key)||groups.set(key,[]).get(key)).push({offset:x,higher:y})}const contexts=[];for(const [key,group] of groups){const fit=logisticFit(group,'offset','higher'),levels=[...new Set(group.map(x=>x.offset))].sort((a,b)=>a-b),hi=group.filter(x=>x.higher).length,lo=group.length-hi,slope=fit.slope,pse=slope>1e-8?-fit.intercept/slope:null,jnd=slope>1e-8?Math.log(3)/slope:null,threshold75=slope>1e-8?(Math.log(3)-fit.intercept)/slope:null,range=levels.length?[levels[0],levels.at(-1)]:[null,null],boot=bootstrapIntonation(group,bootstrapReps,`${key}:${group.length}:${levels.join(',')}`),ci=boot.threshold75Ci95,ciWidth=ci?.every(Number.isFinite)?ci[1]-ci[0]:null,inRange=Number.isFinite(pse)&&Number.isFinite(threshold75)&&pse>=range[0]&&pse<=range[1]&&threshold75>=range[0]&&threshold75<=range[1],bootstrapStable=boot.valid>=Math.ceil(bootstrapReps*.8)&&Number.isFinite(ciWidth)&&ciWidth<=Math.max(12,(range[1]-range[0])*.8),authoritative=group.length>=minTrials&&levels.length>=minLevels&&hi>=minClass&&lo>=minClass&&slope>1e-7&&inRange&&bootstrapStable;contexts.push({contextKey:key,n:group.length,levels:levels.length,classCounts:{higher:hi,lower:lo},rangeCents:range,pseCents:pse,jndCents:jnd,threshold75Cents:threshold75,slope,bootstrapValid:boot.valid,bootstrapReps,pseCi95:boot.pseCi95,jndCi95:boot.jndCi95,threshold75Ci95:boot.threshold75Ci95,diagnostics:{positiveSlope:slope>1e-7,inSampleRange:inRange,bootstrapStable},status:authoritative?'READY':'UNQUALIFIED',authoritative})}return{schema:'earforge.contextual_intonation_pse_jnd.v2',status:contexts.length?(contexts.every(x=>x.authoritative)?'READY':'PARTIAL_OR_UNQUALIFIED'):'ZERO_DATA',contexts,authoritative:contexts.length>0&&contexts.every(x=>x.authoritative),masteryMutation:false,visualRequired:false}}
  function memoryInterferenceCost(rows,{priorAlpha=1.2,priorBeta=1.8,minPerCondition=12}={}){const groups=new Map();for(const row of rows||[]){const key=String(row?.interference||row?.condition||'none');(groups.get(key)||groups.set(key,[]).get(key)).push(row)}const baseline=betaCell(groups.get('none')||[],{priorAlpha,priorBeta}),conditions=[];for(const [condition,group] of groups){const cell=betaCell(group,{priorAlpha,priorBeta}),cost=baseline.estimate-cell.estimate,se=Math.sqrt(baseline.variance+cell.variance);conditions.push({condition,...cell,cost,ci95:[cost-1.96*se,cost+1.96*se],authoritative:baseline.n>=minPerCondition&&cell.n>=minPerCondition})}conditions.sort((a,b)=>b.cost-a.cost);return{schema:'earforge.memory_interference_cost.v1',status:groups.size?'READY':'ZERO_DATA',baseline,conditions,authoritative:baseline.n>=minPerCondition&&conditions.every(x=>x.authoritative),masteryMutation:false,visualRequired:false}}
  function inducedPrototypeShift(rows,{minPerPhase=16}={}){const phases={pre:[],post:[]};for(const row of rows||[]){const phase=String(row?.phase||'').toLowerCase(),value=Number(row?.boundary??row?.center??row?.value);if(phases[phase]&&Number.isFinite(value))phases[phase].push(value)}const pre=mean(phases.pre),post=mean(phases.post),shift=post-pre;return{schema:'earforge.induced_prototype_shift.v1',status:phases.pre.length&&phases.post.length?'READY':'INSUFFICIENT',pre:{n:phases.pre.length,center:pre},post:{n:phases.post.length,center:post},shift,authoritative:phases.pre.length>=minPerPhase&&phases.post.length>=minPerPhase,scope:SESSION_SCOPE,traditionModel:false,masteryMutation:false,visualRequired:false}}
  function polyphonicChangeDetectionProfile(rows,options={}){return{...signalDetectionProfile((rows||[]).map(row=>({...row,targetPresent:Boolean(row?.mutationPresent??row?.targetPresent),responsePresent:Boolean(row?.responseChanged??row?.responsePresent)})),options),schema:'earforge.polyphonic_change_detection.v1'}}

  function validateUnitContract(row){const issues=[];if(!row?.id)issues.push('id');if(!GENERATOR_CONTRACTS[row?.generatorContract])issues.push('generatorContract');if(!JUDGE_CONTRACTS[row?.judgeContract])issues.push('judgeContract');if(!row?.audibleInvariant)issues.push('audibleInvariant');if(!Array.isArray(row?.prereq))issues.push('prereq');if(!Array.isArray(row?.responseModes)||!row.responseModes.includes('choice'))issues.push('responseModes');if(row?.frontierContract?.visualRequired!==false)issues.push('visualRequired');return{ok:!issues.length,issues}}
  function judge(unit,response,reference={}){if(!unit||!JUDGE_CONTRACTS[unit.judgeContract])return{valid:false,correct:false,reason:'unknown_judge'};if(typeof response==='string')return{valid:true,correct:response===unit.id,contract:unit.judgeContract};if(unit.judgeContract.startsWith('voice.')){const result=polyphonicSemanticScore(reference,response);return{valid:result.valid,correct:result.score>=.85,score:result.score,details:result}}if(unit.judgeContract.startsWith('scene.')){const result=analyzeSceneTrial(reference,response,{targetRole:unit.params?.targetRole});return{valid:true,correct:result.changedRoles.includes(unit.params?.targetRole)||unit.params?.code==='masking-continuity'&&result.targetContinuity>.99,score:result.targetContinuity,details:result}}return{valid:true,correct:Boolean(response?.correct),contract:unit.judgeContract}}

  function domainTransferGap(rows,{internalLabel='internal',externalLabels=['independent','external-recording'],retentionWindows=[7,30]}={}){
    const clean=(rows||[]).filter(r=>r&&Number.isFinite(Number(r.correct)));
    const score=xs=>{const n=xs.length,c=xs.reduce((s,r)=>s+(Number(r.correct)>0?1:0),0),lat=xs.map(r=>Number(r.latencyMs)).filter(Number.isFinite).sort((a,b)=>a-b);return{n,accuracy:n?c/n:null,medianLatencyMs:lat.length?lat[Math.floor(lat.length/2)]:null}};
    const internal=score(clean.filter(r=>String(r.renderer)===internalLabel)),outside=score(clean.filter(r=>externalLabels.includes(String(r.renderer))));
    const retention={};for(const days of retentionWindows){const xs=clean.filter(r=>externalLabels.includes(String(r.renderer))&&Number(r.retentionWindowDays)===Number(days));retention[days]={...score(xs),windowDays:Number(days),qualified:xs.length>0}}
    const gap=internal.accuracy!=null&&outside.accuracy!=null?internal.accuracy-outside.accuracy:null,latencyGapMs=internal.medianLatencyMs!=null&&outside.medianLatencyMs!=null?outside.medianLatencyMs-internal.medianLatencyMs:null;
    return{schema:'earforge.domain_transfer_gap.v2',internal,outside,domainTransferGap:gap,latencyGapMs,retention,externalRecordingTrials:clean.filter(r=>r.renderer==='external-recording').length,independentRendererTrials:clean.filter(r=>r.renderer==='independent').length,externalHumanDomainValidated:clean.some(r=>r.renderer==='external-recording'),masteryMutation:false,visualRequired:false}
  }
  function spatialThresholdProfile(rows,{targetDPrime=1.35,minTrials=24,minContexts=3}={}){
    const clean=(rows||[]).filter(r=>Number.isFinite(Number(r?.separationDeg))&&Number(r.separationDeg)>=0),groups=new Map();
    for(const row of clean){const x=Number(row.separationDeg);(groups.get(x)||groups.set(x,[]).get(x)).push(row)}
    const points=[];for(const [deg,g] of groups){const s=signalDetectionProfile(g,{minSignal:1,minNoise:1});if(s.signalTrials&&s.noiseTrials)points.push({x:deg,dPrime:s.dPrime,n:s.signalTrials+s.noiseTrials,criterion:s.criterion})}
    points.sort((a,b)=>a.x-b.x);const fit=weightedLinear(points.map(p=>({x:p.x,y:p.dPrime,w:p.n}))),identifiable=points.length>=3&&Number.isFinite(fit.slope)&&fit.slope>0;
    const rawThreshold=identifiable?(targetDPrime-fit.intercept)/fit.slope:null,threshold=Number.isFinite(rawThreshold)&&rawThreshold>=points[0].x&&rawThreshold<=points.at(-1).x?rawThreshold:null,total=points.reduce((s,p)=>s+p.n,0),contexts={};
    for(const row of clean){const key=`v${Number(row.carrierVariant)||0}@${Number(row.centerAzimuth)||0}`;(contexts[key]??=[]).push(row)}
    const contextProfiles=Object.fromEntries(Object.entries(contexts).map(([key,g])=>{const s=signalDetectionProfile(g,{minSignal:1,minNoise:1});return[key,{n:g.length,dPrime:s.dPrime??null}]})),contextCount=Object.keys(contextProfiles).length;
    return{schema:'earforge.spatial_threshold.v3',status:threshold!=null?'READY':points.length>=2?'UNIDENTIFIABLE':'INSUFFICIENT',targetDPrime,thresholdDeg:threshold,slope:fit.slope,points,trialCount:total,contextProfiles,contextCount,transferContextsMeasured:contextCount>=minContexts,authoritative:threshold!=null&&total>=minTrials&&contextCount>=minContexts,masteryMutation:false,visualRequired:false}
  }
  function expressiveTimingProfile(expectedMs,responseMs,{resyncToleranceMs=75}={}){const e=(expectedMs||[]).map(Number).filter(Number.isFinite),r=(responseMs||[]).map(Number).filter(Number.isFinite),n=Math.min(e.length,r.length);if(n<3)return{schema:'earforge.expressive_timing_profile.v2',valid:false,n,masteryMutation:false};const raw=Array.from({length:n},(_,i)=>r[i]-e[i]),sorted=[...raw].sort((a,b)=>a-b),offset=sorted[Math.floor(sorted.length/2)],errors=raw.map(x=>x-offset),abs=errors.map(Math.abs),meanAbs=abs.reduce((a,b)=>a+b,0)/n,pred=[];for(let i=1;i<n;i++)pred.push(Math.abs((r[i]-r[i-1])-(e[i]-e[i-1])));let perturb=-1;for(let i=2;i<n;i++)if(Math.abs((e[i]-e[i-1])-(e[i-1]-e[i-2]))>20){perturb=i;break}let resyncBeats=null;if(perturb>=0){for(let i=perturb;i<n;i++)if(Math.abs(errors[i])<=resyncToleranceMs){resyncBeats=i-perturb;break}}return{schema:'earforge.expressive_timing_profile.v2',valid:true,n,phaseMaeMs:meanAbs,predictionMaeMs:pred.length?pred.reduce((a,b)=>a+b,0)/pred.length:null,resyncBeats,constantOffsetMs:offset,centeredErrorsMs:errors,translationInvariant:true,physicalLatencyMeasured:false,masteryMutation:false,visualRequired:false}}
  function tempoSlopeThresholdProfile(rows,{targetDPrime=1.35,minTrials=24}={}){
    const clean=(rows||[]).filter(r=>Number.isFinite(Number(r?.slopeBpmPerBeat))&&Number(r.slopeBpmPerBeat)>=0),groups=new Map();
    for(const row of clean){const x=Number(row.slopeBpmPerBeat);(groups.get(x)||groups.set(x,[]).get(x)).push(row)}
    const points=[];for(const [slope,g] of groups){const d=signalDetectionProfile(g,{minSignal:1,minNoise:1});if(d.signalTrials&&d.noiseTrials)points.push({x:slope,dPrime:d.dPrime,n:d.signalTrials+d.noiseTrials,criterion:d.criterion})}
    points.sort((a,b)=>a.x-b.x);const fit=weightedLinear(points.map(p=>({x:p.x,y:p.dPrime,w:p.n}))),identifiable=points.length>=3&&Number.isFinite(fit.slope)&&fit.slope>0,rawThreshold=identifiable?(targetDPrime-fit.intercept)/fit.slope:null;
    const threshold=Number.isFinite(rawThreshold)&&rawThreshold>=points[0].x&&rawThreshold<=points.at(-1).x?rawThreshold:null,total=points.reduce((s,p)=>s+p.n,0);
    return{schema:'earforge.tempo_slope_threshold.v2',status:threshold!=null?'READY':points.length>=2?'UNIDENTIFIABLE':'INSUFFICIENT',targetDPrime,thresholdBpmPerBeat:threshold,slope:fit.slope,points,trialCount:total,authoritative:threshold!=null&&total>=minTrials,masteryMutation:false,visualRequired:false}
  }
  function freeRecallGap({choiceAccuracy=null,recallRows=[]}={}){const rows=(recallRows||[]).filter(r=>r?.score!=null&&Number.isFinite(Number(r.score))),n=rows.length,recall=n?rows.reduce((s,r)=>s+clamp(Number(r.score),0,1),0)/n:null,choice=choiceAccuracy!=null&&Number.isFinite(Number(choiceAccuracy))?clamp(Number(choiceAccuracy),0,1):null,groups={};for(const row of rows)(groups[String(row.kind||'unspecified')]??=[]).push(row);const byKind=Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,{n:v.length,accuracy:v.reduce((a,r)=>a+clamp(Number(r.score),0,1),0)/v.length}]));return{schema:'earforge.choice_free_recall_gap.v2',choiceAccuracy:choice,freeRecallAccuracy:recall,gap:choice!=null&&recall!=null?choice-recall:null,n,byKind,masteryMutation:false,visualRequired:false}}
  function sequenceDistance(a,b){const x=(a||[]).map(v=>String(v)),y=(b||[]).map(v=>String(v)),prev=Array.from({length:y.length+1},(_,i)=>i);for(let i=1;i<=x.length;i++){let diag=prev[0];prev[0]=i;for(let j=1;j<=y.length;j++){const old=prev[j],cost=x[i-1]===y[j-1]?0:1;prev[j]=Math.min(prev[j]+1,prev[j-1]+1,diag+cost);diag=old}}return prev[y.length]}
  function openRecallReconstructionScore(reference={},response={},options={}){const refTokens=Array.isArray(reference.tokens)?reference.tokens:Array.isArray(reference.relativeSemitones)?reference.relativeSemitones:Array.isArray(reference.rhythmOnsets)?reference.rhythmOnsets:Array.isArray(reference.roles)?reference.roles:[],gotTokens=Array.isArray(response.tokens)?response.tokens:Array.isArray(response.relativeSemitones)?response.relativeSemitones:Array.isArray(response.rhythmOnsets)?response.rhythmOnsets:Array.isArray(response.roles)?response.roles:[],editN=Math.max(refTokens.length,gotTokens.length,1),editDistance=refTokens.length||gotTokens.length?sequenceDistance(refTokens,gotTokens):null,editScore=editDistance==null?null:clamp(1-editDistance/editN,0,1),labelRef=String(reference.label||'').trim().toLowerCase(),labelGot=String(response.label||'').trim().toLowerCase(),labelAccuracy=labelRef&&labelGot?(labelRef===labelGot?1:0):null,degreeRef=reference.degrees||reference.relativeSemitones,degreeGot=response.degrees||response.relativeSemitones,degreeErrors=Array.isArray(degreeRef)&&Array.isArray(degreeGot)?sequenceDistance(degreeRef,degreeGot):null,degreeErrorRate=degreeErrors==null?null:degreeErrors/Math.max(degreeRef.length,degreeGot.length,1),harmRef=reference.harmonicFunctions||[],harmGot=response.harmonicFunctions||[],harmonicFunctionAccuracy=harmRef.length&&harmGot.length?clamp(1-sequenceDistance(harmRef,harmGot)/Math.max(harmRef.length,harmGot.length),0,1):null,rRef=reference.rhythmOnsets||[],rGot=response.rhythmOnsets||[],rn=Math.min(rRef.length,rGot.length),rhythmTimingMaeBeats=rn?rRef.slice(0,rn).reduce((s,x,i)=>s+Math.abs(Number(x)-Number(rGot[i])),0)/rn:null,parts=[editScore,labelAccuracy,harmonicFunctionAccuracy,rhythmTimingMaeBeats==null?null:Math.exp(-rhythmTimingMaeBeats)].filter(Number.isFinite),score=parts.length?parts.reduce((a,b)=>a+b,0)/parts.length:null;return{schema:'earforge.open_recall_reconstruction.v1',score,editDistance,normalizedEditScore:editScore,degreeErrorRate,harmonicFunctionAccuracy,rhythmTimingMaeBeats,replays:Math.max(0,Number(options.replays)||0),delayedRetention:Boolean(options.delayed),measuredComponents:parts.length,masteryMutation:false,visualRequired:false}}
  function rendererTransferProfile(rows,{minPerCondition=6}={}){const clean=(rows||[]).filter(r=>typeof r?.correct==='boolean'),group=heldout=>clean.filter(r=>Boolean(r.heldoutRenderer)===heldout),summarize=g=>{const n=g.length,c=g.filter(x=>x.correct).length,lat=g.map(x=>Number(x.latency)).filter(Number.isFinite),conf=g.map(x=>Number(x.confidence)).filter(Number.isFinite);return{n,accuracy:n?c/n:null,latencyMeanMs:lat.length?lat.reduce((a,b)=>a+b,0)/lat.length:null,confidenceMean:conf.length?conf.reduce((a,b)=>a+b,0)/conf.length:null}},familiar=summarize(group(false)),heldout=summarize(group(true)),qualified=familiar.n>=minPerCondition&&heldout.n>=minPerCondition;return{schema:'earforge.renderer_transfer_profile.v1',status:qualified?'READY':'INSUFFICIENT',familiar,heldout,accuracyGap:familiar.accuracy!=null&&heldout.accuracy!=null?familiar.accuracy-heldout.accuracy:null,latencyGapMs:familiar.latencyMeanMs!=null&&heldout.latencyMeanMs!=null?heldout.latencyMeanMs-familiar.latencyMeanMs:null,confidenceGap:familiar.confidenceMean!=null&&heldout.confidenceMean!=null?familiar.confidenceMean-heldout.confidenceMean:null,qualified,masteryMutation:false,visualRequired:false}}
  function sourceSegregationProfile(rows,{minTrials=24}={}){const clean=(rows||[]).filter(r=>Number(r?.sourceCount)>=2&&Number(r?.sourceCount)<=4),counts={};for(const r of clean)(counts[Number(r.sourceCount)]??=[]).push(r);const bySourceCount=Object.fromEntries(Object.entries(counts).map(([k,g])=>[k,{n:g.length,sourceIdentificationAccuracy:g.filter(x=>x.sourceCorrect===true).length/g.length,roleChangesBeforeError:g.map(x=>Number(x.roleChangesBeforeError)).filter(Number.isFinite).reduce((a,b)=>a+b,0)/Math.max(1,g.filter(x=>Number.isFinite(Number(x.roleChangesBeforeError))).length),trajectoryRetention:g.map(x=>Number(x.trajectoryRetention)).filter(Number.isFinite).reduce((a,b)=>a+b,0)/Math.max(1,g.filter(x=>Number.isFinite(Number(x.trajectoryRetention))).length)}])),sceneThreshold=adaptiveSceneThreshold(clean),spatial=spatialThresholdProfile(clean,{minTrials:Math.max(12,Math.floor(minTrials/2)),minContexts:1}),qualified=clean.length>=minTrials&&Object.keys(counts).length>=2;return{schema:'earforge.source_segregation_profile.v1',status:qualified?'READY':'INSUFFICIENT',trialCount:clean.length,sourceCounts:Object.keys(counts).map(Number),bySourceCount,signalMaskThresholdDb:sceneThreshold.thresholdDb,minimumSpatialSeparationDeg:spatial.thresholdDeg,qualified,hrtfIndividualized:false,masteryMutation:false,visualRequired:false}}
  function worldPhraseHeldoutProfile(rows,{minHeldout=24}={}){const all=rows||[],blocked=all.filter(r=>r?.provenanceQualified!==true),clean=all.filter(r=>r?.provenanceQualified===true&&r?.heldout===true),labels=[...new Set(clean.flatMap(r=>[String(r.expectedGrammar||''),String(r.responseGrammar||'')]).filter(Boolean))],matrix=Object.fromEntries(labels.map(a=>[a,Object.fromEntries(labels.map(b=>[b,0]))]));let correct=0,continuation=0,continuationN=0,tonicTransfer=0,timbreTransfer=0;for(const r of clean){const a=String(r.expectedGrammar||''),b=String(r.responseGrammar||'');if(a&&b){if(matrix[a]?.[b]!=null)matrix[a][b]++;if(a===b)correct++}if(typeof r.continuationCorrect==='boolean'){continuationN++;if(r.continuationCorrect)continuation++}if(r.tonicHeldout)tonicTransfer++;if(r.timbreHeldout)timbreTransfer++}const qualified=blocked.length===0&&clean.length>=minHeldout;return{schema:'earforge.world_phrase_heldout_profile.v1',status:blocked.length?'PROVENANCE_REQUIRED':qualified?'READY':'INSUFFICIENT_HELDOUT',heldoutTrials:clean.length,blockedByProvenance:blocked.length,grammarAccuracy:clean.length?correct/clean.length:null,continuationAccuracy:continuationN?continuation/continuationN:null,confusionMatrix:matrix,tonicTransferTrials:tonicTransfer,timbreTransferTrials:timbreTransfer,qualified,masteryMutation:false,visualRequired:false}}
  function assistiveLatencyProfile(rows){
    const clean=(rows||[]).filter(r=>Number.isFinite(Number(r.responseLatencyMs))),groups={};for(const r of clean){const key=String(r.assistiveTech||r.route||'unknown');(groups[key]??=[]).push(r)}
    const medianFinite=(xs,key)=>{const v=xs.filter(r=>r?.[key]!=null).map(r=>Number(r[key])).filter(Number.isFinite).sort((a,b)=>a-b);return v.length?v[Math.floor(v.length/2)]:null};
    const summarize=xs=>{const total=medianFinite(xs,'responseLatencyMs'),delivery=medianFinite(xs,'interfaceDeliveryMs'),perceptual=total!=null&&delivery!=null?Math.max(0,total-delivery):null;return{n:xs.length,responseMedianMs:total,interfaceDeliveryMedianMs:delivery,perceptualPlusDecisionMedianMs:perceptual,physicalScreenReaderLatencyMeasured:false}};
    const summaries=Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,summarize(v)])),pairs=new Map();
    for(const r of clean){const id=String(r.pairId||'');if(!id)continue;const g=pairs.get(id)||{};g[String(r.assistiveTech||r.route||'unknown')]=r;pairs.set(id,g)}
    const pairwise=[];for(const [pairId,g] of pairs){const routes=Object.keys(g);if(routes.length<2)continue;for(let i=0;i<routes.length;i++)for(let j=i+1;j<routes.length;j++){const a=g[routes[i]],b=g[routes[j]],da=Number(a.responseLatencyMs)-Number(a.interfaceDeliveryMs||0),db=Number(b.responseLatencyMs)-Number(b.interfaceDeliveryMs||0);if(Number.isFinite(da)&&Number.isFinite(db))pairwise.push({pairId,a:routes[i],b:routes[j],adjustedDifferenceMs:db-da})}}
    return{schema:'earforge.assistive_latency.v2',groups:summaries,pairedComparisons:pairwise,pairedComparisonCount:pairwise.length,decompositionRequiresMeasuredInterfaceDelivery:true,cohortComparisonQualified:pairwise.length>0,masteryMutation:false,visualRequired:false}
  }
  const validation=(()=>{const issues=[],ids=new Set();for(const row of UNITS){if(ids.has(row.id))issues.push(`duplicate:${row.id}`);ids.add(row.id);const result=validateUnitContract(row);for(const issue of result.issues)issues.push(`${row.id}:${issue}`)}return deepFreeze({ok:!issues.length,issues,count:UNITS.length,generators:Object.keys(GENERATOR_CONTRACTS).length,judges:Object.keys(JUDGE_CONTRACTS).length})})();
  if(!validation.ok)throw new Error(validation.issues.join('; '));
  return deepFreeze({VERSION,SCHEMA,PPQ,SESSION_SCOPE,UNITS,UNIT_BY_ID,GENERATOR_CONTRACTS,JUDGE_CONTRACTS,validation,stableStringify,hash32,validateUnitContract,buildQuestionSpec,judge,analyzeSceneTrial,polyphonicSemanticScore,relationalTimingProfile,inducedPrototypeModel,inducedExpectationModel,hierarchicalIntonationMap,hierarchicalMemoryCapacityProfile,transferAxisMatrix,normalInv,signalDetectionProfile,polyphonicChangeDetectionProfile,transferGradient,adaptiveSceneThreshold,contextualIntonationPseJnd,memoryInterferenceCost,inducedPrototypeShift,domainTransferGap,spatialThresholdProfile,expressiveTimingProfile,tempoSlopeThresholdProfile,freeRecallGap,openRecallReconstructionScore,rendererTransferProfile,sourceSegregationProfile,worldPhraseHeldoutProfile,assistiveLatencyProfile});
});
