'use strict';
(function(root){
  function mount({container,audio,catalog,questions,state,onBack,announce=()=>{}}){
    const P=root.EarForgeProduction,M=root.EarForgeMidiOutput,key='earforge.production.1';let target=null,closed=false,generation=0,busy=false,graded=false,complete=0,replays=0,isolated=[],renderers=[],access=null,midiSerial=0,inputPort=null,outputPort=null,renderer=null;const fields=new Map(),urls=new Set();
    const el=(tag,text='',attrs={})=>{const n=document.createElement(tag);n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n};
    const screen=el('div','',{class:'screen score-screen production-screen'}),back=el('button','Retour',{type:'button'}),heading=el('h1','Reconstruction multivoix',{tabindex:'-1'});back.onclick=onBack;screen.append(back,heading,el('p','Écouter les voix ensemble, puis reconstruire chacune sans portée. La première note de chaque voix est donnée. Les résultats restent séparés de la maîtrise du parcours.'));
    function control(parent,label,node){const wrap=el('label',label);wrap.append(node);parent.append(wrap);return node}
    function options(select,values){select.replaceChildren(...values.map(([value,text])=>el('option',text,{value})));}
    const settings=el('fieldset');settings.append(el('legend','Exercice'));
    const count=control(settings,'Nombre de voix',el('select','',{id:'production-count'}));options(count,[[2,'Deux'],[3,'Trois'],[4,'Quatre']]);
    const mode=control(settings,'Saisie',el('select','',{id:'production-mode'}));options(mode,[['relative','Demi-tons depuis la note de départ'],['notes','Noms de notes ou numéros MIDI']]);
    const fresh=el('button','Nouvelle phrase',{type:'button',id:'production-new'});settings.append(fresh);screen.append(settings);
    const help=el('p','En demi-tons, écrire 0 +2 +4 pour la note de départ, puis deux et quatre demi-tons au-dessus. En notes, écrire do4 ré4 mi4 ou 60 62 64. Ici, do4 correspond au numéro MIDI 60. Les durées sont entendues mais ne sont pas notées dans cet exercice.');screen.append(help);
    const status=el('p','',{role:'status','aria-live':'polite','aria-atomic':'true',id:'production-status'}),play=el('button','Écouter toutes les voix',{type:'button',id:'production-play'}),stop=el('button','Arrêter',{type:'button'}),answers=el('div','',{id:'production-answers'}),submit=el('button','Évaluer la reconstruction',{type:'button',id:'production-submit'}),result=el('section','',{id:'production-result',tabindex:'-1','aria-label':'Résultat de reconstruction'});
    const midi=el('details'),midiTitle=el('summary','Clavier et son MIDI facultatifs'),connect=el('button','Connecter le MIDI',{type:'button',id:'production-connect'}),midiStatus=el('p','Aucune connexion demandée.',{role:'status',id:'production-midi-status'});midi.append(midiTitle,el('p','Le clavier peut saisir les notes d’une voix. Une sortie sélectionnée joue un piano externe sur des canaux séparés : aucun son EarForge n’est alors utilisé pour cet exercice. Le matériel et sa latence ne sont pas calibrés. Aucun microphone n’est demandé.'),connect,midiStatus);
    const input=control(midi,'Entrée MIDI',el('select','',{id:'production-input'})),output=control(midi,'Sortie sonore',el('select','',{id:'production-output'})),entryVoice=control(midi,'Voix saisie par MIDI',el('select','',{id:'production-input-voice'}));options(input,[['','Sans clavier MIDI']]);options(output,[['','Instruments EarForge']]);input.disabled=true;
    screen.append(midi,play,stop,status,answers,submit,result);
    const exportButton=el('button','Exporter les résultats locaux',{type:'button'});screen.append(exportButton);container.replaceChildren(screen);heading.focus();
    function update(){play.disabled=busy||!target;submit.disabled=busy||graded||complete===0;fresh.disabled=busy;count.disabled=busy;for(const {listen}of fields.values())listen.disabled=busy;mode.disabled=busy||graded;}
    function halt(){generation++;audio.stop();renderer?.finish();busy=false;update();}
    function freshTrial(){halt();try{target=P.create({catalog,questions,state,voices:Number(count.value),seed:Date.now()+':'+generation+':'+Math.random(),timestamp:Date.now()});graded=false;complete=0;replays=0;isolated=[];renderers=[];fields.clear();answers.replaceChildren();result.replaceChildren();options(entryVoice,target.voices.map(v=>[v.id,v.label]));
      for(const v of target.voices){const group=el('fieldset');group.append(el('legend',v.label),el('p','Départ : '+P.noteName(v.start)+'. '+v.notes.length+' notes à reconstruire.'));const field=control(group,'Réponse, '+v.label,el('input','',{type:'text',autocomplete:'off',spellcheck:'false',maxlength:4096,'data-voice':v.id})),listen=el('button','Écouter seulement '+v.label,{type:'button'});listen.onclick=()=>listenTo(v.id);field.onfocus=()=>{entryVoice.value=v.id};field.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(!submit.disabled)evaluate()}};group.append(listen);answers.append(group);fields.set(v.id,{field,listen});}
      status.textContent='Phrase prête. Écoutez toutes les voix avant de valider.';update();
    }catch(e){target=null;status.textContent=e.message;update();}}
    async function listenTo(role=null){
      if(!target||busy)return;halt();const token=++generation;busy=true;update();const spec=role?P.voiceSpec(target,role):target.spec;
      try{const plan=audio.preparePlan(spec);const playback=await audio.playTimeline(plan,{lead:audio.schedulerLead(spec),renderer:outputPort?renderer:null});if(token!==generation||closed)return;status.textContent=role?'Écoute isolée. Cette aide est enregistrée.':'Écoute en cours.';if(!graded){replays++;if(role)isolated.push(role);renderers.push(outputPort?renderer.id:'earforge');}
        await audio.wait(playback);if(token!==generation||closed)return;if(!role)complete++;status.textContent='Écoute terminée. '+replays+' écoute'+(replays>1?'s':'')+'.';
      }catch(e){if(token!==generation||closed)return;status.textContent=e.code==='EARFORGE_PLAY_CANCELLED'?'Lecture arrêtée.':e.message;}
      finally{if(token===generation&&!closed){busy=false;update();}}
    }
    function history(){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x.filter(r=>r?.schema==='earforge.reconstruction.result.v1'&&Array.isArray(r.perVoice)&&Number.isFinite(r.accuracy)).slice(-499):[]}catch{return[]}}
    function evaluate(){if(submit.disabled||!target)return;try{const responses={};for(const v of target.voices)responses[v.id]=P.parse(fields.get(v.id).field.value,{mode:mode.value,start:v.start});const record=P.score(target,responses,{replays,isolated,renderers,mode:mode.value});let stored=true;try{localStorage.setItem(key,JSON.stringify([...history(),record]));}catch{stored=false;}
      graded=true;for(const {field}of fields.values())field.disabled=true;result.replaceChildren(el('h2','Résultat'),el('p',Math.round(record.accuracy*100)+' pour cent de précision des séquences. Distance d’édition : '+record.editDistance+'. '+(record.assisted?'Écoute assistée par voix isolées.':'Écoute globale, sans voix isolée.')));
      for(const row of record.perVoice){const p=el('p',row.label+' : '+row.exact+' notes exactes sur '+row.expectedCount+'. Contour : '+(row.contourAccuracy===null?'non mesurable':Math.round(row.contourAccuracy*100)+' pour cent')+'. Erreur moyenne de hauteur : '+(row.meanPitchError===null?'non mesurable':row.meanPitchError.toFixed(2)+' demi-tons')+'. Réponse : '+row.expected.map(P.noteName).join(', ')+'.'+(row.possibleVoiceSwaps.length?' Attribution possiblement inversée avec '+row.possibleVoiceSwaps.join(', ')+'.':''));result.append(p);}
      result.append(el('p','Les durées, les degrés fonctionnels et la rétention différée ne sont pas notés ici. Aucun crédit de maîtrise n’a été ajouté au parcours.'));status.textContent=stored?'Résultat conservé sur cet appareil.':'Résultat calculé mais non conservé : stockage indisponible.';update();result.focus();
    }catch(e){status.textContent='Réponse à corriger : '+e.message;}}
    function onMessage(event){if(closed||busy||graded||!target)return;const data=event.data;if(!data||data.length<3||(data[0]&0xf0)!==0x90||data[2]===0)return;const v=target.voices.find(v=>v.id===entryVoice.value),item=fields.get(v?.id);if(!item)return;const n=Number(data[1]);if(n<0||n>127)return;if(item.field.value.trim().split(/[\s,;]+/).filter(Boolean).length>=128)return;item.field.value+=(item.field.value?' ':'')+String(mode.value==='relative'?n-v.start:n);announce(v.label+', '+P.noteName(n));}
    function dropInput(){if(inputPort){inputPort.removeEventListener('midimessage',onMessage);try{Promise.resolve(inputPort.close()).catch(()=>{})}catch{}inputPort=null;}}
    function dropOutput(){renderer?.dispose();renderer=null;if(outputPort){try{Promise.resolve(outputPort.close()).catch(()=>{})}catch{}outputPort=null;}}
    function refreshPorts(){if(!access||closed)return;const oldIn=input.value,oldOut=output.value;options(input,[['','Sans clavier MIDI'],...[...access.inputs.values()].filter(p=>p.state!=='disconnected').map(p=>[p.id,p.name||'Clavier MIDI'])]);options(output,[['','Instruments EarForge'],...[...access.outputs.values()].filter(p=>p.state!=='disconnected').map(p=>[p.id,p.name||'Sortie MIDI'])]);input.value=[...input.options].some(o=>o.value===oldIn)?oldIn:'';output.value=[...output.options].some(o=>o.value===oldOut)?oldOut:'';input.disabled=access.inputs.size===0;
      if(inputPort?.state==='disconnected')dropInput();if(outputPort?.state==='disconnected'){halt();dropOutput();output.value='';midiStatus.textContent='Sortie déconnectée. Les prochaines écoutes utilisent EarForge.';}}
    async function connectMidi(){const token=++midiSerial;connect.disabled=true;try{if(typeof navigator.requestMIDIAccess!=='function')throw new Error('Web MIDI n’est pas disponible dans ce navigateur. La saisie texte reste disponible.');const next=await navigator.requestMIDIAccess({sysex:false});if(closed||token!==midiSerial)return;if(access)access.removeEventListener('statechange',refreshPorts);access=next;access.addEventListener('statechange',refreshPorts);refreshPorts();midiStatus.textContent='MIDI disponible. Sélectionnez volontairement une entrée ou une sortie.';}catch(e){if(!closed&&token===midiSerial)midiStatus.textContent=e.message;}finally{if(!closed)connect.disabled=false;}}
    input.onchange=async()=>{dropInput();const token=++midiSerial,port=access?.inputs.get(input.value);if(!port)return;try{await port.open();if(closed||token!==midiSerial){await port.close();return}inputPort=port;port.addEventListener('midimessage',onMessage);midiStatus.textContent='Clavier prêt. Choisissez la voix saisie.';}catch(e){if(!closed)midiStatus.textContent=e.message;}};
    output.onchange=async()=>{halt();dropOutput();const token=++midiSerial,port=access?.outputs.get(output.value);if(!port){midiStatus.textContent='Instruments EarForge sélectionnés.';return}try{await port.open();if(closed||token!==midiSerial){await port.close();return}renderer=new M.Renderer(port);outputPort=port;midiStatus.textContent='Piano externe sélectionné. Programme MIDI un, voix sur canaux distincts.';}catch(e){output.value='';dropOutput();if(!closed)midiStatus.textContent=e.message;}};
    exportButton.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(history(),null,2)],{type:'application/json'}));urls.add(url);const a=el('a','',{href:url,download:'earforge-reconstructions.json'});screen.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url)},1000)};
    mode.onchange=()=>{for(const {field}of fields.values())field.value='';status.textContent='Mode de saisie changé. Réponses effacées pour éviter une interprétation différente.';};connect.onclick=connectMidi;fresh.onclick=freshTrial;play.onclick=()=>listenTo();submit.onclick=evaluate;stop.onclick=()=>{halt();status.textContent='Lecture arrêtée.';};function keydown(e){if(e.key==='Escape'){e.preventDefault();halt();status.textContent='Lecture arrêtée.';}}document.addEventListener('keydown',keydown);freshTrial();
    return{dispose(){closed=true;midiSerial++;halt();dropInput();dropOutput();access?.removeEventListener('statechange',refreshPorts);document.removeEventListener('keydown',keydown);for(const u of urls)URL.revokeObjectURL(u);urls.clear();target=null;fields.clear();}};
  }
  root.EarForgeProductionView={mount};
})(globalThis);
