'use strict';
(function(root){
  const labels=root.EarForgeInstruments.labels;
  const demo='<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>Exemple à deux voix</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name><score-instrument id="I1"><instrument-name>Piano</instrument-name></score-instrument><midi-instrument id="I1"><midi-channel>1</midi-channel><midi-program>1</midi-program></midi-instrument></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>2</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><direction><sound tempo="96"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration><voice>1</voice><type>quarter</type></note><note><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration><voice>1</voice><type>quarter</type></note><note><pitch><step>G</step><octave>4</octave></pitch><duration>4</duration><tie type="start"/><voice>1</voice><type>half</type><notations><tied type="start"/></notations></note><backup><duration>8</duration></backup><note><pitch><step>C</step><octave>3</octave></pitch><duration>8</duration><voice>2</voice><type>whole</type></note></measure><measure number="2"><note><pitch><step>G</step><octave>4</octave></pitch><duration>4</duration><tie type="stop"/><voice>1</voice><type>half</type><notations><tied type="stop"/></notations></note><note><pitch><step>C</step><octave>5</octave></pitch><duration>4</duration><voice>1</voice><type>half</type></note><backup><duration>8</duration></backup><note><pitch><step>C</step><octave>3</octave></pitch><duration>8</duration><voice>2</voice><type>whole</type></note></measure></part></score-partwise>';
  function mount({container,audio,onBack,announce=()=>{},stopSpeech=()=>{},speak=null}){
    const M=root.EarForgeScoreModel,I=root.EarForgeScoreImport,O=root.EarForgeScoreOral,P=root.EarForgeScorePlayer;let score=null,index=0,closed=false,loadGeneration=0,speechGeneration=0;const urls=new Set();
    const el=(tag,text='',attrs={})=>{const n=document.createElement(tag);if(text)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n};
    const screen=el('div','',{class:'screen score-screen'}),top=el('div','',{class:'topline'}),back=el('button','Retour',{type:'button',class:'back'}),heading=el('h1','Partition accessible',{tabindex:'-1'});top.append(back);screen.append(top,heading,el('p','Importer une partition, dicter chaque mesure et écouter ses voix. Cet outil ne modifie pas votre maîtrise du parcours.',{class:'lead'}));back.onclick=onBack;
    function control(parent,label,node){const id='score-'+label.toLowerCase().replace(/[^a-z]+/g,'-');node.id=id;const wrap=el('div','',{class:'score-control'});wrap.append(el('label',label,{for:id}),node);parent.append(wrap);return node}
    const input=control(screen,'Fichier MusicXML',el('input','',{type:'file',accept:'.xml,.musicxml,.mxl,application/xml,application/vnd.recordare.musicxml+xml'})),sample=el('button','Ouvrir un exemple',{type:'button',class:'secondary'});screen.append(sample,el('p','Fichiers XML et MusicXML : huit mégaoctets maximum. MXL compressé : seize mégaoctets maximum. Tout reste sur cet appareil.'));
    const status=el('p','Aucune partition ouverte.',{role:'status','aria-live':'polite','aria-atomic':'true',id:'score-status'}),details=el('details'),summary=el('summary','Limites de lecture'),limitations=el('p','Lecture dans l’ordre écrit. Les reprises et sauts ne sont pas déroulés. Agréments, trilles, pédales et autres indications non réalisées sont signalés. Aucun accompagnement n’est inventé.');details.append(summary,limitations);screen.append(status,details);
    const controls=el('fieldset'),legend=el('legend','Écoute et sélection');controls.append(legend);controls.disabled=true;
    const part=control(controls,'Partie',el('select')),voice=control(controls,'Voix',el('select')),timbre=control(controls,'Instrument',el('select')),tempo=control(controls,'Tempo pour écouter',el('input','',{type:'number',min:10,max:600,step:1,placeholder:'Du fichier, sinon 80','aria-describedby':'score-tempo-info'}));controls.append(el('p','Laisser vide pour respecter les tempos du fichier. Si aucun tempo n’est fourni, la noire à quatre-vingts est une proposition d’écoute, pas une donnée de la partition.',{id:'score-tempo-info'}));
    const style=control(controls,'Style de dictée',el('select'));style.append(el('option','Orale, repères métriques',{value:'oral'}),el('option','Détaillée, positions exactes',{value:'exact'}));
    timbre.append(el('option','Automatique selon la partie',{value:'auto'}));for(const name of P.instruments)timbre.append(el('option',labels[name]||name,{value:name}));
    const nav=el('div','',{class:'score-buttons'}),prev=el('button','Mesure précédente',{type:'button',id:'score-prev'}),next=el('button','Mesure suivante',{type:'button',id:'score-next'}),jump=control(controls,'Numéro de position',el('input','',{type:'number',min:1,step:1,value:1})),go=el('button','Aller à cette mesure',{type:'button'});nav.append(prev,next,go);controls.append(nav);
    const buttons=el('div','',{class:'score-buttons'}),playMeasure=el('button','Écouter la mesure',{type:'button',id:'score-play-measure'}),playAll=el('button','Écouter le morceau',{type:'button',id:'score-play-all'}),stop=el('button','Arrêter',{type:'button',id:'score-stop'}),read=el('button','Dicter la mesure à voix haute',{type:'button',id:'score-speak'}),exportText=el('button','Exporter la dictée en texte',{type:'button',id:'score-export'});buttons.append(playMeasure,playAll,stop,read,exportText);controls.append(buttons);
    const conceal=control(controls,'Masquer la dictée avant écoute',el('input','',{type:'checkbox'})),reveal=el('button','Révéler la dictée',{type:'button',id:'score-reveal'});controls.append(reveal);screen.append(controls);
    const transcript=el('div','',{id:'score-transcript',tabindex:'0','aria-label':'Dictée de la mesure'}),warnings=el('details'),ws=el('summary','Réserves de cette partition'),wt=el('div');warnings.append(ws,wt);screen.append(transcript,warnings);container.replaceChildren(screen);heading.focus();
    const player=new P.Player(audio,{onState:(state,data)=>{if(closed)return;if(state==='playing'){status.textContent='Lecture en cours.'+(data.warnings.length?' '+data.warnings.join(' '):'')}else if(state==='error')status.textContent=data.message;else if(state==='ended')status.textContent='Lecture terminée.';else status.textContent='Lecture arrêtée.'},onMeasure:i=>{if(i!==index){index=i;render(false)}}});
    function cancelSpeech(){speechGeneration++;stopSpeech();}
    function halt(){player.stop();cancelSpeech()}
    function options(){return{style:style.value,part:part.value||null,voice:voice.value||null,instrument:timbre.value,tempo:tempo.value?Number(tempo.value):null}}
    function fillVoices(){voice.replaceChildren(el('option','Toutes les voix',{value:''}));for(const v of [...new Set(score.E.filter(e=>!part.value||e.part===part.value).map(e=>e.voice))])voice.append(el('option','Voix '+v,{value:v}))}
    function render(say=true){if(!score)return;index=Math.max(0,Math.min(score.measures.length-1,index));jump.value=index+1;jump.max=score.measures.length;prev.disabled=index===0;next.disabled=index===score.measures.length-1;const content=O.measure(score,index,options());transcript.replaceChildren(...content.split('\n\n').map(t=>el('p',t)));transcript.hidden=conceal.checked;reveal.hidden=!conceal.checked;read.disabled=conceal.checked||!root.speechSynthesis||typeof speak!=='function';read.title=root.speechSynthesis?'':'Utiliser le lecteur d’écran pour lire la dictée.';if(say)announce('Mesure '+O.natural(score.measures[index].number)+'.')}
    function commit(s){if(!s.validation.ok)throw new Error('Structure de partition incohérente.');if(!s.measures.length)throw new Error('Partition sans mesure.');score=s;index=0;controls.disabled=false;part.replaceChildren(el('option','Toutes les parties',{value:''}));for(const p of score.parts)part.append(el('option',p.name,{value:p.id}));fillVoices();wt.replaceChildren(...[...new Set(score.U.map(u=>u.message))].map(t=>el('p',t)));ws.textContent=score.U.length?'Réserves et interprétations partielles : '+score.U.length:'Aucune réserve détectée sur les éléments pris en charge';status.textContent=(score.title||score.sourceName||'Partition')+'. '+score.measures.length+' mesures, '+score.parts.length+' parties. '+score.U.length+' réserves.';render();}
    input.onchange=async()=>{const file=input.files?.[0];if(!file)return;halt();const token=++loadGeneration;status.textContent='Lecture du fichier…';try{const s=await I.load(file);if(!closed&&token===loadGeneration)commit(s)}catch(error){if(!closed&&token===loadGeneration)status.textContent='Import refusé : '+error.message+(score?' La partition précédente reste ouverte.':'')}};
    sample.onclick=()=>{halt();loadGeneration++;try{commit(M.parse(demo))}catch(error){status.textContent=error.message}};
    style.onchange=()=>{halt();render(false)};part.onchange=()=>{halt();fillVoices();render()};voice.onchange=()=>{halt();render()};timbre.onchange=halt;tempo.onchange=halt;
    prev.onclick=()=>{halt();index--;render()};next.onclick=()=>{halt();index++;render()};go.onclick=()=>{halt();const n=Number(jump.value);if(!Number.isInteger(n)||n<1||n>score.measures.length){status.textContent='Position de mesure invalide.';return}index=n-1;render()};conceal.onchange=()=>{cancelSpeech();render(false)};reveal.onclick=()=>{conceal.checked=false;render(false);transcript.focus()};
    async function play(whole){cancelSpeech();try{const plan=P.compile(score,{...options(),from:whole?0:index,to:whole?score.measures.length-1:index});if(!plan.events.length){status.textContent='Aucun son pris en charge dans cette sélection.';return}await player.play(plan)}catch(error){status.textContent=error.message}}
    playMeasure.onclick=()=>play(false);playAll.onclick=()=>play(true);stop.onclick=halt;
    read.onclick=async()=>{halt();const token=++speechGeneration;status.textContent='Dictée vocale en cours.';try{const result=await speak(O.measure(score,index,options()));if(closed||token!==speechGeneration)return;status.textContent=result.spoken?'Dictée vocale terminée.':'Dictée vocale interrompue. Le texte reste accessible.';}catch{if(!closed&&token===speechGeneration)status.textContent='Dictée vocale indisponible. Le texte reste accessible.'}};
    exportText.onclick=()=>{const url=URL.createObjectURL(new Blob([O.all(score,options())],{type:'text/plain;charset=utf-8'}));urls.add(url);const a=el('a','',{href:url,download:'dictee-earforge.txt'});screen.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);urls.delete(url)},1000)};
    function keydown(e){if(e.key==='Escape'){e.preventDefault();halt()}}screen.addEventListener('keydown',keydown);
    return{dispose(){closed=true;loadGeneration++;halt();player.dispose();screen.removeEventListener('keydown',keydown);for(const u of urls)URL.revokeObjectURL(u);urls.clear();score=null},getScore:()=>score,getPlayer:()=>player};
  }
  root.EarForgeScoreView={mount,example:demo};
})(globalThis);
