'use strict';
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./singing.js'):root.EarForgeSinging,typeof module==='object'&&module.exports?require('./singing-capture.js'):root.EarForgeSingingCapture);if(typeof module==='object'&&module.exports)module.exports=api;else root.EarForgeSingingView=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Singing,CaptureAPI){
 const MESSAGES={time_limit:'Microphone arrêté après la durée maximale. Cet essai n’a pas été évalué.',permission:'Autorisation du microphone refusée. Vous pouvez continuer sans chanter.',missing:'Aucun microphone disponible.',device:'Microphone indisponible ou utilisé ailleurs.',unsupported:'Microphone indisponible ici. Utilisez HTTPS ou localhost et un navigateur compatible.',audio:'Le microphone n’a pas pu démarrer.',permission_timeout:'Demande interrompue. Une autorisation tardive ne démarrera pas le microphone.',device_lost:'Microphone interrompu. Cet essai ne sera pas évalué.',hidden:'Microphone arrêté en quittant la page. Cet essai ne sera pas évalué.',audio_interrupted:'Audio interrompu. Cet essai ne sera pas évalué.',sampling_interrupted:'Capture interrompue. Cet essai ne sera pas évalué.',analysis_error:'Analyse interrompue. Cet essai ne sera pas évalué.',too_long:'Trop de notes pour cet essai. Le microphone est arrêté.',cancelled:'Microphone arrêté. Aucun résultat enregistré.'};
 function resultText(r){if(!r.evaluable)return'Microphone arrêté. Aucun résultat musical : aucune suite de notes stable et exploitable. Réessayez dans un endroit plus calme, avec une note tenue au moins une demi-seconde.';if(r.correct)return`Microphone arrêté. Reproduction correcte : ${r.observed} note${r.observed>1?'s':''}. L’octave globale est libre ; le rythme n’est pas évalué.`;if(r.reason==='note_count')return`Microphone arrêté. ${r.observed} notes détectées pour ${r.expected} attendues. Détachez les notes répétées par un bref silence.`;const i=r.errorsCents.findIndex(e=>Math.abs(e)>50),e=r.errorsCents[i];return`Microphone arrêté. La note ${i+1} est trop ${e>0?'haute':'basse'} d’environ ${Math.round(Math.abs(e))} cents par rapport au modèle. Le rythme n’est pas évalué.`;}
 function mount({container,question,playGuide,beforeCapture=()=>{},onRecord=()=>{},onExit=()=>{}}){
  const doc=container.ownerDocument,button=(id,text)=>{const b=doc.createElement('button');b.id=id;b.type='button';b.textContent=text;return b;},heading=doc.createElement('h2'),help=doc.createElement('p'),status=doc.createElement('p'),actions=doc.createElement('div');
  heading.textContent=question.prompt;help.textContent='Écoutez puis chantez chaque note environ une demi-seconde, à une octave confortable. Détachez les répétitions. Les écouteurs évitent que le modèle ou le lecteur d’écran entre dans le microphone. Aucun enregistrement audio n’est conservé ni envoyé. Chantez seulement quand le bouton indique « Arrêter et évaluer ». Vous pouvez toujours revenir sans chanter.';
  status.id='singing-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');status.setAttribute('aria-atomic','true');
  const replay=button('singing-replay','Écouter le modèle'),start=button('singing-start','Démarrer le microphone'),stop=button('singing-stop','Arrêter et évaluer'),cancel=button('singing-cancel','Annuler la capture'),exit=button('singing-exit','Revenir à la question');actions.className='form-grid';actions.append(replay,start,stop,cancel,exit);container.replaceChildren(heading,help,actions,status);stop.hidden=cancel.hidden=true;start.disabled=true;
  let disposed=false,serial=0,guideReady=false,attempt=0,lastState='idle';
  const capture=new CaptureAPI.Capture({onState:({state,reason})=>{if(disposed)return;lastState=state;const active=['requesting','settling','listening'].includes(state);start.disabled=active||!guideReady;replay.disabled=active;cancel.hidden=!active;stop.hidden=!['settling','listening'].includes(state);stop.disabled=state!=='listening';if(state==='requesting')status.textContent='Autorisation du microphone en cours. Annuler reste disponible.';else if(state==='settling'){status.textContent='Microphone ouvert. Attendez la fin de la préparation.';stop.textContent='Préparation du microphone';}else if(state==='listening'){status.textContent='Microphone prêt. Chantez, puis arrêtez pour évaluer.';stop.textContent='Arrêter et évaluer';stop.focus();}else if(state==='error'||state==='interrupted'){status.textContent=MESSAGES[reason]||'Microphone arrêté. Aucun résultat enregistré.';start.focus();}},onResult:observation=>{if(disposed)return;const result=Singing.evaluate(question.singingTarget,observation);status.textContent=resultText(result);if(result.evaluable){attempt++;onRecord(observation,result,attempt);}start.textContent='Réessayer avec le microphone';exit.focus();}});
  async function listen(){if(disposed)return;const token=++serial;capture.cancel();guideReady=false;start.disabled=replay.disabled=true;status.textContent='Lecture du modèle. Le microphone est arrêté.';try{await playGuide(question);if(disposed||token!==serial)return;guideReady=true;start.disabled=replay.disabled=false;status.textContent='Modèle terminé. Le microphone reste arrêté jusqu’à votre demande.';start.focus();}catch{if(disposed||token!==serial)return;replay.disabled=false;status.textContent='Lecture interrompue. Réécoutez avant de démarrer le microphone.';replay.focus();}}
  replay.addEventListener('click',listen);start.addEventListener('click',()=>{if(disposed||!guideReady||['requesting','settling','listening'].includes(lastState))return;beforeCapture();capture.start();});stop.addEventListener('click',()=>capture.stop());cancel.addEventListener('click',()=>capture.cancel());exit.addEventListener('click',()=>{if(!disposed){dispose();onExit();}});
  const onKey=e=>{if(e.key==='Escape'){e.preventDefault();capture.cancel();}};container.addEventListener('keydown',onKey);
  function dispose(){if(disposed)return;disposed=true;serial++;container.removeEventListener('keydown',onKey);capture.dispose();}
  listen();return{dispose,capture};
 }
 return{mount,resultText};
});
