'use strict';
const CACHE='earforge-11-19-0-v2';
const ROOT=new URL('./',self.location.href).href;
const SCOPE_PATH=new URL('./',self.location.href).pathname;
const INDEX_PATH=new URL('index.html',ROOT).pathname;
const ASSETS=["","app-11.19.0-audio-kernel.js","app-11.19.0-storage.js","apple-touch-icon.png","earforge-11.19.0.webmanifest","earforge-performance-aliases.js","earforge-performance-manifest.json","icon-192.png","icon-512.png","index.html","loader-11.19.0.js","maskable-512.png","payload/app/00.txt","payload/app/01.txt","payload/app/02.txt","payload/app/03.txt","payload/app/04.txt","payload/app/05.txt","payload/app/06.txt","payload/app/07.txt","payload/audio/00.txt","payload/audio/01.txt","payload/audio/02.txt","payload/catalog/00.txt","payload/catalog/01.txt","payload/catalog/02.txt","payload/catalog/03.txt","payload/catalog/04.txt","payload/catalog/05.txt","payload/catalog/06.txt","payload/direct1119/frontiers/00.txt","payload/direct1119/frontiers/01.txt","payload/direct1119/frontiers/02.txt","payload/direct1119/frontiers/03.txt","payload/direct1119/frontiers/04.txt","payload/direct1119/labs/00.txt","payload/direct1119/labs/01.txt","payload/direct1119/labs/02.txt","payload/direct1119/labs/03.txt","payload/direct1119/perfRuntime/00.txt","payload/direct1119/perfRuntime/01.txt","payload/direct1119/perfRuntime/02.txt","payload/direct1119/perfRuntime/03.txt","payload/direct1119/perfRuntime/04.txt","payload/learning/00.txt","payload/learning/01.txt","payload/learning/02.txt","payload/learning/03.txt","payload/learning/04.txt","payload/learning/05.txt","payload/learning/06.txt","payload/learning/07.txt","payload/questions/00.txt","payload/questions/01.txt","payload/questions/02.txt","payload/questions/03.txt","payload/questions/04.txt","payload/questions/05.txt","payload/questions/06.txt","payload/questions/07a.txt","payload/questions/07b.txt","payload/questions/07c.txt","payload/questions/08a.txt","payload/questions/08b.txt","payload/questions/08c1.txt","payload/questions/08c2.txt","payload/questions/09.txt","styles-11.19.0.css","styles1119/00.css","styles1119/01.css","styles1119/02.css","styles1119/03.css","styles1119/04.css","styles1119/05.css"].map(name=>new URL(name||'./',ROOT).href);
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('earforge-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin||!url.pathname.startsWith(SCOPE_PATH))return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{if(response&&response.ok&&(url.pathname===SCOPE_PATH||url.pathname===INDEX_PATH))caches.open(CACHE).then(cache=>cache.put(ROOT,response.clone()));return response}).catch(()=>caches.match(ROOT)));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response&&response.ok)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response})))})
